// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2019.1
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="DigitRec,hls_ip_2019_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=1,HLS_INPUT_PART=xcku5p-ffvb676-2-e,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=6.473594,HLS_SYN_LAT=-1898726292,HLS_SYN_TPT=none,HLS_SYN_MEM=287,HLS_SYN_DSP=4,HLS_SYN_FF=1480,HLS_SYN_LUT=3083,HLS_VERSION=2019_1}" *)

module DigitRec (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        global_training_set_V_address0,
        global_training_set_V_ce0,
        global_training_set_V_q0,
        global_test_set_V_address0,
        global_test_set_V_ce0,
        global_test_set_V_q0,
        global_results_address0,
        global_results_ce0,
        global_results_we0,
        global_results_d0,
        num_training,
        num_test
);

parameter    ap_ST_fsm_state1 = 17'd1;
parameter    ap_ST_fsm_state2 = 17'd2;
parameter    ap_ST_fsm_state3 = 17'd4;
parameter    ap_ST_fsm_state4 = 17'd8;
parameter    ap_ST_fsm_state5 = 17'd16;
parameter    ap_ST_fsm_state6 = 17'd32;
parameter    ap_ST_fsm_state7 = 17'd64;
parameter    ap_ST_fsm_state8 = 17'd128;
parameter    ap_ST_fsm_state9 = 17'd256;
parameter    ap_ST_fsm_state10 = 17'd512;
parameter    ap_ST_fsm_state11 = 17'd1024;
parameter    ap_ST_fsm_state12 = 17'd2048;
parameter    ap_ST_fsm_state13 = 17'd4096;
parameter    ap_ST_fsm_state14 = 17'd8192;
parameter    ap_ST_fsm_state15 = 17'd16384;
parameter    ap_ST_fsm_state16 = 17'd32768;
parameter    ap_ST_fsm_state17 = 17'd65536;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [14:0] global_training_set_V_address0;
output   global_training_set_V_ce0;
input  [255:0] global_training_set_V_q0;
output  [10:0] global_test_set_V_address0;
output   global_test_set_V_ce0;
input  [255:0] global_test_set_V_q0;
output  [10:0] global_results_address0;
output   global_results_ce0;
output   global_results_we0;
output  [7:0] global_results_d0;
input  [31:0] num_training;
input  [31:0] num_test;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg global_training_set_V_ce0;
reg global_test_set_V_ce0;
reg global_results_ce0;
reg global_results_we0;

(* fsm_encoding = "none" *) reg   [16:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg   [14:0] training_set_V_address0;
reg    training_set_V_ce0;
reg    training_set_V_we0;
wire   [255:0] training_set_V_q0;
reg   [10:0] test_set_V_address0;
reg    test_set_V_ce0;
reg    test_set_V_we0;
wire   [255:0] test_set_V_q0;
reg   [10:0] results_address0;
reg    results_ce0;
reg    results_we0;
wire   [7:0] results_q0;
wire   [14:0] i_fu_449_p2;
reg   [14:0] i_reg_814;
wire    ap_CS_fsm_state2;
wire   [63:0] zext_ln172_fu_455_p1;
reg   [63:0] zext_ln172_reg_819;
wire   [0:0] icmp_ln169_fu_443_p2;
wire   [30:0] i_5_fu_469_p2;
reg   [30:0] i_5_reg_832;
wire    ap_CS_fsm_state4;
wire   [63:0] zext_ln179_fu_475_p1;
reg   [63:0] zext_ln179_reg_837;
wire   [0:0] icmp_ln176_fu_464_p2;
wire   [28:0] iter_cnt_fu_544_p2;
reg   [28:0] iter_cnt_reg_847;
wire   [30:0] t_fu_559_p2;
reg   [30:0] t_reg_855;
wire    ap_CS_fsm_state6;
wire   [63:0] zext_ln189_fu_565_p1;
reg   [63:0] zext_ln189_reg_860;
wire   [0:0] icmp_ln185_fu_554_p2;
reg   [255:0] test_instance_V_reg_870;
wire    ap_CS_fsm_state7;
wire   [4:0] i_6_fu_576_p2;
wire    ap_CS_fsm_state8;
wire   [14:0] zext_ln199_fu_587_p1;
reg   [14:0] zext_ln199_reg_883;
wire    ap_CS_fsm_state9;
wire   [28:0] zext_ln199_1_fu_591_p1;
reg   [28:0] zext_ln199_1_reg_888;
wire   [0:0] icmp_ln199_fu_595_p2;
reg   [0:0] icmp_ln199_reg_893;
wire   [10:0] i_8_fu_601_p2;
reg   [10:0] i_8_reg_897;
wire   [3:0] j_fu_617_p2;
reg   [3:0] j_reg_905;
wire    ap_CS_fsm_state10;
wire   [0:0] icmp_ln202_fu_611_p2;
wire   [5:0] sub_ln209_fu_641_p2;
reg   [5:0] sub_ln209_reg_915;
wire   [255:0] ret_V_fu_651_p2;
reg   [255:0] ret_V_reg_924;
wire    ap_CS_fsm_state11;
wire   [8:0] i_9_fu_666_p2;
wire    ap_CS_fsm_state12;
wire   [8:0] cnt_fu_683_p2;
wire   [0:0] icmp_ln17_fu_660_p2;
wire   [31:0] zext_ln35_fu_689_p1;
reg   [31:0] zext_ln35_reg_942;
wire   [31:0] zext_ln47_fu_693_p1;
reg   [31:0] zext_ln47_reg_947;
wire    ap_CS_fsm_state13;
wire   [1:0] k_fu_703_p2;
reg   [1:0] k_reg_955;
wire   [0:0] icmp_ln42_fu_697_p2;
wire   [14:0] add_ln202_fu_747_p2;
wire   [31:0] select_ln44_fu_763_p3;
wire    ap_CS_fsm_state14;
wire   [31:0] select_ln44_1_fu_771_p3;
wire   [30:0] i_7_fu_787_p2;
reg   [30:0] i_7_reg_986;
wire    ap_CS_fsm_state16;
wire   [63:0] zext_ln224_fu_793_p1;
reg   [63:0] zext_ln224_reg_991;
wire   [0:0] icmp_ln221_fu_782_p2;
reg   [4:0] knn_set_address0;
reg    knn_set_ce0;
reg    knn_set_we0;
reg   [10:0] knn_set_d0;
wire   [10:0] knn_set_q0;
wire    grp_knn_vote_fu_437_ap_start;
wire    grp_knn_vote_fu_437_ap_done;
wire    grp_knn_vote_fu_437_ap_idle;
wire    grp_knn_vote_fu_437_ap_ready;
wire   [4:0] grp_knn_vote_fu_437_knn_set_address0;
wire    grp_knn_vote_fu_437_knn_set_ce0;
wire   [7:0] grp_knn_vote_fu_437_ap_return;
reg   [14:0] i_0_reg_290;
wire    ap_CS_fsm_state3;
reg   [30:0] i1_0_reg_301;
wire    ap_CS_fsm_state5;
reg   [30:0] t_0_reg_312;
wire    ap_CS_fsm_state15;
reg   [4:0] i2_0_reg_323;
wire   [0:0] icmp_ln192_fu_570_p2;
reg   [10:0] i3_0_reg_334;
wire   [0:0] icmp_ln211_fu_647_p2;
reg   [14:0] indvars_iv_reg_345;
reg   [3:0] j_0_reg_357;
reg   [8:0] dist_reg_368;
reg   [8:0] bvh_d_index_reg_380;
reg   [31:0] max_dist_0_i_reg_391;
reg   [31:0] max_dist_id_0_i_reg_403;
reg   [1:0] max_dist_id_reg_415;
reg   [30:0] i4_0_reg_426;
wire    ap_CS_fsm_state17;
reg    grp_knn_vote_fu_437_ap_start_reg;
wire   [63:0] zext_ln196_fu_582_p1;
wire   [63:0] zext_ln206_fu_628_p1;
wire   [63:0] zext_ln44_1_fu_718_p1;
wire  signed [63:0] sext_ln53_fu_737_p1;
wire   [0:0] icmp_ln52_fu_723_p2;
wire   [10:0] zext_ln53_fu_742_p1;
wire   [31:0] zext_ln176_fu_460_p1;
wire  signed [31:0] sext_ln182_fu_480_p0;
wire  signed [31:0] mul_ln182_fu_483_p0;
wire   [64:0] mul_ln182_fu_483_p2;
wire  signed [31:0] tmp_7_fu_495_p1;
wire   [64:0] sub_ln182_fu_489_p2;
wire   [0:0] tmp_7_fu_495_p3;
wire   [28:0] tmp_8_fu_502_p4;
wire   [28:0] tmp_9_fu_512_p4;
wire   [28:0] select_ln182_fu_522_p3;
wire   [28:0] sub_ln182_1_fu_530_p2;
wire   [28:0] select_ln182_1_fu_536_p3;
wire   [31:0] zext_ln185_fu_550_p1;
wire   [14:0] add_ln206_fu_623_p2;
wire   [5:0] shl_ln_fu_633_p3;
wire   [5:0] j_0_cast2_fu_607_p1;
wire   [31:0] zext_ln35_1_fu_656_p1;
wire   [0:0] p_Result_s_fu_672_p3;
wire   [8:0] zext_ln18_fu_679_p1;
wire   [5:0] zext_ln44_fu_709_p1;
wire   [5:0] add_ln44_fu_713_p2;
wire   [5:0] trunc_ln53_fu_728_p1;
wire   [5:0] add_ln53_fu_732_p2;
wire  signed [31:0] max_dist_fu_753_p1;
wire   [0:0] icmp_ln44_fu_757_p2;
wire   [31:0] zext_ln221_fu_778_p1;
reg   [16:0] ap_NS_fsm;

// power-on initialization
initial begin
#0 ap_CS_fsm = 17'd1;
#0 grp_knn_vote_fu_437_ap_start_reg = 1'b0;
end

DigitRec_trainingcud #(
    .DataWidth( 256 ),
    .AddressRange( 18000 ),
    .AddressWidth( 15 ))
training_set_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(training_set_V_address0),
    .ce0(training_set_V_ce0),
    .we0(training_set_V_we0),
    .d0(global_training_set_V_q0),
    .q0(training_set_V_q0)
);

DigitRec_test_set_V #(
    .DataWidth( 256 ),
    .AddressRange( 2000 ),
    .AddressWidth( 11 ))
test_set_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(test_set_V_address0),
    .ce0(test_set_V_ce0),
    .we0(test_set_V_we0),
    .d0(global_test_set_V_q0),
    .q0(test_set_V_q0)
);

DigitRec_results #(
    .DataWidth( 8 ),
    .AddressRange( 2000 ),
    .AddressWidth( 11 ))
results_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(results_address0),
    .ce0(results_ce0),
    .we0(results_we0),
    .d0(grp_knn_vote_fu_437_ap_return),
    .q0(results_q0)
);

DigitRec_knn_set #(
    .DataWidth( 11 ),
    .AddressRange( 30 ),
    .AddressWidth( 5 ))
knn_set_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(knn_set_address0),
    .ce0(knn_set_ce0),
    .we0(knn_set_we0),
    .d0(knn_set_d0),
    .q0(knn_set_q0)
);

knn_vote grp_knn_vote_fu_437(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_knn_vote_fu_437_ap_start),
    .ap_done(grp_knn_vote_fu_437_ap_done),
    .ap_idle(grp_knn_vote_fu_437_ap_idle),
    .ap_ready(grp_knn_vote_fu_437_ap_ready),
    .knn_set_address0(grp_knn_vote_fu_437_knn_set_address0),
    .knn_set_ce0(grp_knn_vote_fu_437_knn_set_ce0),
    .knn_set_q0(knn_set_q0),
    .ap_return(grp_knn_vote_fu_437_ap_return)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_knn_vote_fu_437_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state10) & ((icmp_ln199_reg_893 == 1'd1) | ((icmp_ln211_fu_647_p2 == 1'd1) & (icmp_ln202_fu_611_p2 == 1'd1))))) begin
            grp_knn_vote_fu_437_ap_start_reg <= 1'b1;
        end else if ((grp_knn_vote_fu_437_ap_ready == 1'b1)) begin
            grp_knn_vote_fu_437_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state12) & (icmp_ln17_fu_660_p2 == 1'd0))) begin
        bvh_d_index_reg_380 <= i_9_fu_666_p2;
    end else if ((1'b1 == ap_CS_fsm_state11)) begin
        bvh_d_index_reg_380 <= 9'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state12) & (icmp_ln17_fu_660_p2 == 1'd0))) begin
        dist_reg_368 <= cnt_fu_683_p2;
    end else if ((1'b1 == ap_CS_fsm_state11)) begin
        dist_reg_368 <= 9'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln169_fu_443_p2 == 1'd1))) begin
        i1_0_reg_301 <= 31'd0;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        i1_0_reg_301 <= i_5_reg_832;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state8) & (icmp_ln192_fu_570_p2 == 1'd0))) begin
        i2_0_reg_323 <= i_6_fu_576_p2;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        i2_0_reg_323 <= 5'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state8) & (icmp_ln192_fu_570_p2 == 1'd1))) begin
        i3_0_reg_334 <= 11'd0;
    end else if (((1'b1 == ap_CS_fsm_state10) & (icmp_ln202_fu_611_p2 == 1'd1) & (icmp_ln211_fu_647_p2 == 1'd0) & (icmp_ln199_reg_893 == 1'd0))) begin
        i3_0_reg_334 <= i_8_reg_897;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state6) & (icmp_ln185_fu_554_p2 == 1'd0))) begin
        i4_0_reg_426 <= 31'd0;
    end else if ((1'b1 == ap_CS_fsm_state17)) begin
        i4_0_reg_426 <= i_7_reg_986;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        i_0_reg_290 <= i_reg_814;
    end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        i_0_reg_290 <= 15'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state9) & (icmp_ln199_fu_595_p2 == 1'd0))) begin
        indvars_iv_reg_345 <= 15'd0;
    end else if (((1'b1 == ap_CS_fsm_state13) & (icmp_ln42_fu_697_p2 == 1'd1))) begin
        indvars_iv_reg_345 <= add_ln202_fu_747_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state9) & (icmp_ln199_fu_595_p2 == 1'd0))) begin
        j_0_reg_357 <= 4'd0;
    end else if (((1'b1 == ap_CS_fsm_state13) & (icmp_ln42_fu_697_p2 == 1'd1))) begin
        j_0_reg_357 <= j_reg_905;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state12) & (icmp_ln17_fu_660_p2 == 1'd1))) begin
        max_dist_0_i_reg_391 <= 32'd0;
    end else if ((1'b1 == ap_CS_fsm_state14)) begin
        max_dist_0_i_reg_391 <= select_ln44_fu_763_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state12) & (icmp_ln17_fu_660_p2 == 1'd1))) begin
        max_dist_id_0_i_reg_403 <= 32'd4;
    end else if ((1'b1 == ap_CS_fsm_state14)) begin
        max_dist_id_0_i_reg_403 <= select_ln44_1_fu_771_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state12) & (icmp_ln17_fu_660_p2 == 1'd1))) begin
        max_dist_id_reg_415 <= 2'd0;
    end else if ((1'b1 == ap_CS_fsm_state14)) begin
        max_dist_id_reg_415 <= k_reg_955;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_knn_vote_fu_437_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state15))) begin
        t_0_reg_312 <= t_reg_855;
    end else if (((1'b1 == ap_CS_fsm_state4) & (icmp_ln176_fu_464_p2 == 1'd0))) begin
        t_0_reg_312 <= 31'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        i_5_reg_832 <= i_5_fu_469_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state16)) begin
        i_7_reg_986 <= i_7_fu_787_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        i_8_reg_897 <= i_8_fu_601_p2;
        icmp_ln199_reg_893 <= icmp_ln199_fu_595_p2;
        zext_ln199_1_reg_888[10 : 0] <= zext_ln199_1_fu_591_p1[10 : 0];
        zext_ln199_reg_883[10 : 0] <= zext_ln199_fu_587_p1[10 : 0];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        i_reg_814 <= i_fu_449_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state4) & (icmp_ln176_fu_464_p2 == 1'd0))) begin
        iter_cnt_reg_847 <= iter_cnt_fu_544_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state10) & (icmp_ln199_reg_893 == 1'd0))) begin
        j_reg_905 <= j_fu_617_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state13)) begin
        k_reg_955 <= k_fu_703_p2;
        zext_ln47_reg_947[1 : 0] <= zext_ln47_fu_693_p1[1 : 0];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        ret_V_reg_924 <= ret_V_fu_651_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state10) & (icmp_ln202_fu_611_p2 == 1'd0) & (icmp_ln199_reg_893 == 1'd0))) begin
        sub_ln209_reg_915 <= sub_ln209_fu_641_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        t_reg_855 <= t_fu_559_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        test_instance_V_reg_870 <= test_set_V_q0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln169_fu_443_p2 == 1'd0))) begin
        zext_ln172_reg_819[14 : 0] <= zext_ln172_fu_455_p1[14 : 0];
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state4) & (icmp_ln176_fu_464_p2 == 1'd1))) begin
        zext_ln179_reg_837[30 : 0] <= zext_ln179_fu_475_p1[30 : 0];
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state6) & (icmp_ln185_fu_554_p2 == 1'd1))) begin
        zext_ln189_reg_860[30 : 0] <= zext_ln189_fu_565_p1[30 : 0];
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state16) & (icmp_ln221_fu_782_p2 == 1'd1))) begin
        zext_ln224_reg_991[30 : 0] <= zext_ln224_fu_793_p1[30 : 0];
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state12) & (icmp_ln17_fu_660_p2 == 1'd1))) begin
        zext_ln35_reg_942[8 : 0] <= zext_ln35_fu_689_p1[8 : 0];
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state16) & (icmp_ln221_fu_782_p2 == 1'd0))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state16) & (icmp_ln221_fu_782_p2 == 1'd0))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state17)) begin
        global_results_ce0 = 1'b1;
    end else begin
        global_results_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state17)) begin
        global_results_we0 = 1'b1;
    end else begin
        global_results_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        global_test_set_V_ce0 = 1'b1;
    end else begin
        global_test_set_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        global_training_set_V_ce0 = 1'b1;
    end else begin
        global_training_set_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state13) & (icmp_ln52_fu_723_p2 == 1'd1) & (icmp_ln42_fu_697_p2 == 1'd1))) begin
        knn_set_address0 = sext_ln53_fu_737_p1;
    end else if (((1'b1 == ap_CS_fsm_state13) & (icmp_ln42_fu_697_p2 == 1'd0))) begin
        knn_set_address0 = zext_ln44_1_fu_718_p1;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        knn_set_address0 = zext_ln196_fu_582_p1;
    end else if ((1'b1 == ap_CS_fsm_state15)) begin
        knn_set_address0 = grp_knn_vote_fu_437_knn_set_address0;
    end else begin
        knn_set_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state8) | ((1'b1 == ap_CS_fsm_state13) & (icmp_ln52_fu_723_p2 == 1'd1) & (icmp_ln42_fu_697_p2 == 1'd1)) | ((1'b1 == ap_CS_fsm_state13) & (icmp_ln42_fu_697_p2 == 1'd0)))) begin
        knn_set_ce0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state15)) begin
        knn_set_ce0 = grp_knn_vote_fu_437_knn_set_ce0;
    end else begin
        knn_set_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state13) & (icmp_ln52_fu_723_p2 == 1'd1) & (icmp_ln42_fu_697_p2 == 1'd1))) begin
        knn_set_d0 = zext_ln53_fu_742_p1;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        knn_set_d0 = 11'd256;
    end else begin
        knn_set_d0 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_CS_fsm_state13) & (icmp_ln52_fu_723_p2 == 1'd1) & (icmp_ln42_fu_697_p2 == 1'd1)) | ((1'b1 == ap_CS_fsm_state8) & (icmp_ln192_fu_570_p2 == 1'd0)))) begin
        knn_set_we0 = 1'b1;
    end else begin
        knn_set_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state16)) begin
        results_address0 = zext_ln224_fu_793_p1;
    end else if ((1'b1 == ap_CS_fsm_state15)) begin
        results_address0 = zext_ln189_reg_860;
    end else begin
        results_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state16) | ((grp_knn_vote_fu_437_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state15)))) begin
        results_ce0 = 1'b1;
    end else begin
        results_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((grp_knn_vote_fu_437_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state15))) begin
        results_we0 = 1'b1;
    end else begin
        results_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        test_set_V_address0 = zext_ln189_fu_565_p1;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        test_set_V_address0 = zext_ln179_reg_837;
    end else begin
        test_set_V_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state6))) begin
        test_set_V_ce0 = 1'b1;
    end else begin
        test_set_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        test_set_V_we0 = 1'b1;
    end else begin
        test_set_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        training_set_V_address0 = zext_ln206_fu_628_p1;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        training_set_V_address0 = zext_ln172_reg_819;
    end else begin
        training_set_V_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state10))) begin
        training_set_V_ce0 = 1'b1;
    end else begin
        training_set_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        training_set_V_we0 = 1'b1;
    end else begin
        training_set_V_we0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln169_fu_443_p2 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state2;
        end
        ap_ST_fsm_state4 : begin
            if (((1'b1 == ap_CS_fsm_state4) & (icmp_ln176_fu_464_p2 == 1'd0))) begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state6 : begin
            if (((1'b1 == ap_CS_fsm_state6) & (icmp_ln185_fu_554_p2 == 1'd0))) begin
                ap_NS_fsm = ap_ST_fsm_state16;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state8 : begin
            if (((1'b1 == ap_CS_fsm_state8) & (icmp_ln192_fu_570_p2 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state9;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state8;
            end
        end
        ap_ST_fsm_state9 : begin
            ap_NS_fsm = ap_ST_fsm_state10;
        end
        ap_ST_fsm_state10 : begin
            if (((1'b1 == ap_CS_fsm_state10) & (icmp_ln202_fu_611_p2 == 1'd1) & (icmp_ln211_fu_647_p2 == 1'd0) & (icmp_ln199_reg_893 == 1'd0))) begin
                ap_NS_fsm = ap_ST_fsm_state9;
            end else if (((1'b1 == ap_CS_fsm_state10) & ((icmp_ln199_reg_893 == 1'd1) | ((icmp_ln211_fu_647_p2 == 1'd1) & (icmp_ln202_fu_611_p2 == 1'd1))))) begin
                ap_NS_fsm = ap_ST_fsm_state15;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state11;
            end
        end
        ap_ST_fsm_state11 : begin
            ap_NS_fsm = ap_ST_fsm_state12;
        end
        ap_ST_fsm_state12 : begin
            if (((1'b1 == ap_CS_fsm_state12) & (icmp_ln17_fu_660_p2 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state13;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state12;
            end
        end
        ap_ST_fsm_state13 : begin
            if (((1'b1 == ap_CS_fsm_state13) & (icmp_ln42_fu_697_p2 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state10;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state14;
            end
        end
        ap_ST_fsm_state14 : begin
            ap_NS_fsm = ap_ST_fsm_state13;
        end
        ap_ST_fsm_state15 : begin
            if (((grp_knn_vote_fu_437_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state15))) begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state15;
            end
        end
        ap_ST_fsm_state16 : begin
            if (((1'b1 == ap_CS_fsm_state16) & (icmp_ln221_fu_782_p2 == 1'd0))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state17;
            end
        end
        ap_ST_fsm_state17 : begin
            ap_NS_fsm = ap_ST_fsm_state16;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln202_fu_747_p2 = (indvars_iv_reg_345 + 15'd1800);

assign add_ln206_fu_623_p2 = (indvars_iv_reg_345 + zext_ln199_reg_883);

assign add_ln44_fu_713_p2 = (zext_ln44_fu_709_p1 + sub_ln209_reg_915);

assign add_ln53_fu_732_p2 = (trunc_ln53_fu_728_p1 + sub_ln209_reg_915);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state10 = ap_CS_fsm[32'd9];

assign ap_CS_fsm_state11 = ap_CS_fsm[32'd10];

assign ap_CS_fsm_state12 = ap_CS_fsm[32'd11];

assign ap_CS_fsm_state13 = ap_CS_fsm[32'd12];

assign ap_CS_fsm_state14 = ap_CS_fsm[32'd13];

assign ap_CS_fsm_state15 = ap_CS_fsm[32'd14];

assign ap_CS_fsm_state16 = ap_CS_fsm[32'd15];

assign ap_CS_fsm_state17 = ap_CS_fsm[32'd16];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd7];

assign ap_CS_fsm_state9 = ap_CS_fsm[32'd8];

assign cnt_fu_683_p2 = (zext_ln18_fu_679_p1 + dist_reg_368);

assign global_results_address0 = zext_ln224_reg_991;

assign global_results_d0 = results_q0;

assign global_test_set_V_address0 = zext_ln179_fu_475_p1;

assign global_training_set_V_address0 = zext_ln172_fu_455_p1;

assign grp_knn_vote_fu_437_ap_start = grp_knn_vote_fu_437_ap_start_reg;

assign i_5_fu_469_p2 = (i1_0_reg_301 + 31'd1);

assign i_6_fu_576_p2 = (i2_0_reg_323 + 5'd1);

assign i_7_fu_787_p2 = (i4_0_reg_426 + 31'd1);

assign i_8_fu_601_p2 = (i3_0_reg_334 + 11'd1);

assign i_9_fu_666_p2 = (bvh_d_index_reg_380 + 9'd1);

assign i_fu_449_p2 = (i_0_reg_290 + 15'd1);

assign icmp_ln169_fu_443_p2 = ((i_0_reg_290 == 15'd18000) ? 1'b1 : 1'b0);

assign icmp_ln176_fu_464_p2 = (($signed(zext_ln176_fu_460_p1) < $signed(num_test)) ? 1'b1 : 1'b0);

assign icmp_ln17_fu_660_p2 = ((bvh_d_index_reg_380 == 9'd256) ? 1'b1 : 1'b0);

assign icmp_ln185_fu_554_p2 = (($signed(zext_ln185_fu_550_p1) < $signed(num_test)) ? 1'b1 : 1'b0);

assign icmp_ln192_fu_570_p2 = ((i2_0_reg_323 == 5'd30) ? 1'b1 : 1'b0);

assign icmp_ln199_fu_595_p2 = ((i3_0_reg_334 == 11'd1800) ? 1'b1 : 1'b0);

assign icmp_ln202_fu_611_p2 = ((j_0_reg_357 == 4'd10) ? 1'b1 : 1'b0);

assign icmp_ln211_fu_647_p2 = ((zext_ln199_1_reg_888 == iter_cnt_reg_847) ? 1'b1 : 1'b0);

assign icmp_ln221_fu_782_p2 = (($signed(zext_ln221_fu_778_p1) < $signed(num_test)) ? 1'b1 : 1'b0);

assign icmp_ln42_fu_697_p2 = ((max_dist_id_reg_415 == 2'd3) ? 1'b1 : 1'b0);

assign icmp_ln44_fu_757_p2 = (($signed(max_dist_fu_753_p1) > $signed(max_dist_0_i_reg_391)) ? 1'b1 : 1'b0);

assign icmp_ln52_fu_723_p2 = (($signed(zext_ln35_reg_942) < $signed(max_dist_0_i_reg_391)) ? 1'b1 : 1'b0);

assign iter_cnt_fu_544_p2 = ($signed(select_ln182_1_fu_536_p3) + $signed(29'd536870911));

assign j_0_cast2_fu_607_p1 = j_0_reg_357;

assign j_fu_617_p2 = (j_0_reg_357 + 4'd1);

assign k_fu_703_p2 = (max_dist_id_reg_415 + 2'd1);

assign max_dist_fu_753_p1 = $signed(knn_set_q0);

assign mul_ln182_fu_483_p0 = sext_ln182_fu_480_p0;

assign mul_ln182_fu_483_p2 = ($signed(mul_ln182_fu_483_p0) * $signed(65'h19999999A));

assign p_Result_s_fu_672_p3 = ret_V_reg_924[zext_ln35_1_fu_656_p1];

assign ret_V_fu_651_p2 = (training_set_V_q0 ^ test_instance_V_reg_870);

assign select_ln182_1_fu_536_p3 = ((tmp_7_fu_495_p3[0:0] === 1'b1) ? sub_ln182_1_fu_530_p2 : tmp_9_fu_512_p4);

assign select_ln182_fu_522_p3 = ((tmp_7_fu_495_p3[0:0] === 1'b1) ? tmp_8_fu_502_p4 : tmp_9_fu_512_p4);

assign select_ln44_1_fu_771_p3 = ((icmp_ln44_fu_757_p2[0:0] === 1'b1) ? zext_ln47_reg_947 : max_dist_id_0_i_reg_403);

assign select_ln44_fu_763_p3 = ((icmp_ln44_fu_757_p2[0:0] === 1'b1) ? max_dist_fu_753_p1 : max_dist_0_i_reg_391);

assign sext_ln182_fu_480_p0 = num_training;

assign sext_ln53_fu_737_p1 = $signed(add_ln53_fu_732_p2);

assign shl_ln_fu_633_p3 = {{j_0_reg_357}, {2'd0}};

assign sub_ln182_1_fu_530_p2 = (29'd0 - select_ln182_fu_522_p3);

assign sub_ln182_fu_489_p2 = (65'd0 - mul_ln182_fu_483_p2);

assign sub_ln209_fu_641_p2 = (shl_ln_fu_633_p3 - j_0_cast2_fu_607_p1);

assign t_fu_559_p2 = (t_0_reg_312 + 31'd1);

assign tmp_7_fu_495_p1 = num_training;

assign tmp_7_fu_495_p3 = tmp_7_fu_495_p1[32'd31];

assign tmp_8_fu_502_p4 = {{sub_ln182_fu_489_p2[64:36]}};

assign tmp_9_fu_512_p4 = {{mul_ln182_fu_483_p2[64:36]}};

assign trunc_ln53_fu_728_p1 = max_dist_id_0_i_reg_403[5:0];

assign zext_ln172_fu_455_p1 = i_0_reg_290;

assign zext_ln176_fu_460_p1 = i1_0_reg_301;

assign zext_ln179_fu_475_p1 = i1_0_reg_301;

assign zext_ln185_fu_550_p1 = t_0_reg_312;

assign zext_ln189_fu_565_p1 = t_0_reg_312;

assign zext_ln18_fu_679_p1 = p_Result_s_fu_672_p3;

assign zext_ln196_fu_582_p1 = i2_0_reg_323;

assign zext_ln199_1_fu_591_p1 = i3_0_reg_334;

assign zext_ln199_fu_587_p1 = i3_0_reg_334;

assign zext_ln206_fu_628_p1 = add_ln206_fu_623_p2;

assign zext_ln221_fu_778_p1 = i4_0_reg_426;

assign zext_ln224_fu_793_p1 = i4_0_reg_426;

assign zext_ln35_1_fu_656_p1 = bvh_d_index_reg_380;

assign zext_ln35_fu_689_p1 = dist_reg_368;

assign zext_ln44_1_fu_718_p1 = add_ln44_fu_713_p2;

assign zext_ln44_fu_709_p1 = max_dist_id_reg_415;

assign zext_ln47_fu_693_p1 = max_dist_id_reg_415;

assign zext_ln53_fu_742_p1 = dist_reg_368;

always @ (posedge ap_clk) begin
    zext_ln172_reg_819[63:15] <= 49'b0000000000000000000000000000000000000000000000000;
    zext_ln179_reg_837[63:31] <= 33'b000000000000000000000000000000000;
    zext_ln189_reg_860[63:31] <= 33'b000000000000000000000000000000000;
    zext_ln199_reg_883[14:11] <= 4'b0000;
    zext_ln199_1_reg_888[28:11] <= 18'b000000000000000000;
    zext_ln35_reg_942[31:9] <= 23'b00000000000000000000000;
    zext_ln47_reg_947[31:2] <= 30'b000000000000000000000000000000;
    zext_ln224_reg_991[63:31] <= 33'b000000000000000000000000000000000;
end

endmodule //DigitRec
