// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2019.1
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "knn_vote.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic knn_vote::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic knn_vote::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<12> knn_vote::ap_ST_fsm_state1 = "1";
const sc_lv<12> knn_vote::ap_ST_fsm_state2 = "10";
const sc_lv<12> knn_vote::ap_ST_fsm_state3 = "100";
const sc_lv<12> knn_vote::ap_ST_fsm_state4 = "1000";
const sc_lv<12> knn_vote::ap_ST_fsm_state5 = "10000";
const sc_lv<12> knn_vote::ap_ST_fsm_state6 = "100000";
const sc_lv<12> knn_vote::ap_ST_fsm_state7 = "1000000";
const sc_lv<12> knn_vote::ap_ST_fsm_state8 = "10000000";
const sc_lv<12> knn_vote::ap_ST_fsm_state9 = "100000000";
const sc_lv<12> knn_vote::ap_ST_fsm_state10 = "1000000000";
const sc_lv<12> knn_vote::ap_ST_fsm_state11 = "10000000000";
const sc_lv<12> knn_vote::ap_ST_fsm_state12 = "100000000000";
const sc_lv<32> knn_vote::ap_const_lv32_0 = "00000000000000000000000000000000";
const sc_lv<32> knn_vote::ap_const_lv32_1 = "1";
const sc_lv<32> knn_vote::ap_const_lv32_2 = "10";
const sc_lv<32> knn_vote::ap_const_lv32_3 = "11";
const sc_lv<1> knn_vote::ap_const_lv1_0 = "0";
const sc_lv<32> knn_vote::ap_const_lv32_4 = "100";
const sc_lv<32> knn_vote::ap_const_lv32_5 = "101";
const sc_lv<32> knn_vote::ap_const_lv32_6 = "110";
const sc_lv<1> knn_vote::ap_const_lv1_1 = "1";
const sc_lv<32> knn_vote::ap_const_lv32_7 = "111";
const sc_lv<32> knn_vote::ap_const_lv32_8 = "1000";
const sc_lv<32> knn_vote::ap_const_lv32_A = "1010";
const sc_lv<32> knn_vote::ap_const_lv32_B = "1011";
const sc_lv<2> knn_vote::ap_const_lv2_0 = "00";
const sc_lv<4> knn_vote::ap_const_lv4_0 = "0000";
const sc_lv<32> knn_vote::ap_const_lv32_3E8 = "1111101000";
const sc_lv<2> knn_vote::ap_const_lv2_3 = "11";
const sc_lv<32> knn_vote::ap_const_lv32_9 = "1001";
const sc_lv<8> knn_vote::ap_const_lv8_0 = "00000000";
const sc_lv<32> knn_vote::ap_const_lv32_100 = "100000000";
const sc_lv<2> knn_vote::ap_const_lv2_1 = "1";
const sc_lv<4> knn_vote::ap_const_lv4_A = "1010";
const sc_lv<4> knn_vote::ap_const_lv4_1 = "1";
const sc_lv<32> knn_vote::ap_const_lv32_1F = "11111";
const sc_lv<30> knn_vote::ap_const_lv30_0 = "000000000000000000000000000000";
const sc_lv<2> knn_vote::ap_const_lv2_2 = "10";
const bool knn_vote::ap_const_boolean_1 = true;

knn_vote::knn_vote(sc_module_name name) : sc_module(name), mVcdFile(0) {
    vote_list_U = new knn_vote_vote_list("vote_list_U");
    vote_list_U->clk(ap_clk);
    vote_list_U->reset(ap_rst);
    vote_list_U->address0(vote_list_address0);
    vote_list_U->ce0(vote_list_ce0);
    vote_list_U->we0(vote_list_we0);
    vote_list_U->d0(vote_list_d0);
    vote_list_U->q0(vote_list_q0);
    vote_list_U->address1(vote_list_address1);
    vote_list_U->ce1(vote_list_ce1);
    vote_list_U->q1(vote_list_q1);
    DigitRec_mux_32_3bkb_U1 = new DigitRec_mux_32_3bkb<1,1,32,32,32,2,32>("DigitRec_mux_32_3bkb_U1");
    DigitRec_mux_32_3bkb_U1->din0(min_distance_list_2_1_fu_100);
    DigitRec_mux_32_3bkb_U1->din1(min_distance_list_2_3_fu_104);
    DigitRec_mux_32_3bkb_U1->din2(min_distance_list_2_2_fu_108);
    DigitRec_mux_32_3bkb_U1->din3(r_0_reg_219);
    DigitRec_mux_32_3bkb_U1->dout(tmp_3_fu_495_p5);
    DigitRec_mux_32_3bkb_U2 = new DigitRec_mux_32_3bkb<1,1,32,32,32,2,32>("DigitRec_mux_32_3bkb_U2");
    DigitRec_mux_32_3bkb_U2->din0(label_list_2_1_fu_112);
    DigitRec_mux_32_3bkb_U2->din1(label_list_2_3_fu_116);
    DigitRec_mux_32_3bkb_U2->din2(label_list_2_2_fu_120);
    DigitRec_mux_32_3bkb_U2->din3(i4_0_reg_253);
    DigitRec_mux_32_3bkb_U2->dout(tmp_1_fu_882_p5);

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_add_ln105_fu_461_p2);
    sensitive << ( sub_ln105_reg_1085 );
    sensitive << ( zext_ln98_fu_445_p1 );

    SC_METHOD(thread_add_ln129_fu_899_p2);
    sensitive << ( vote_list_q0 );

    SC_METHOD(thread_ap_CS_fsm_state1);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state10);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state11);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state12);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state2);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state3);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state4);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state5);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state6);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state7);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state8);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state9);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( ap_CS_fsm_state11 );
    sensitive << ( icmp_ln136_fu_906_p2 );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( ap_CS_fsm_state11 );
    sensitive << ( icmp_ln136_fu_906_p2 );

    SC_METHOD(thread_ap_return);
    sensitive << ( ap_CS_fsm_state11 );
    sensitive << ( icmp_ln136_fu_906_p2 );
    sensitive << ( max_vote_0_reg_264 );
    sensitive << ( ap_return_preg );

    SC_METHOD(thread_i_1_fu_372_p2);
    sensitive << ( i1_0_reg_186 );

    SC_METHOD(thread_i_2_fu_876_p2);
    sensitive << ( i4_0_reg_253 );

    SC_METHOD(thread_i_3_fu_421_p2);
    sensitive << ( label_list_2_21_reg_197 );

    SC_METHOD(thread_i_4_fu_912_p2);
    sensitive << ( i5_0_reg_276 );

    SC_METHOD(thread_i_fu_330_p2);
    sensitive << ( i_0_reg_175 );

    SC_METHOD(thread_icmp_ln102_fu_483_p2);
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( r_0_reg_219 );

    SC_METHOD(thread_icmp_ln105_1_fu_522_p2);
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( icmp_ln102_fu_483_p2 );
    sensitive << ( tmp_4_fu_512_p4 );

    SC_METHOD(thread_icmp_ln105_fu_507_p2);
    sensitive << ( min_distance_list_2_21_reg_1103 );
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( icmp_ln102_fu_483_p2 );
    sensitive << ( tmp_3_fu_495_p5 );

    SC_METHOD(thread_icmp_ln108_fu_560_p2);
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( r3_0_reg_242 );

    SC_METHOD(thread_icmp_ln111_fu_576_p2);
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( icmp_ln108_fu_560_p2 );
    sensitive << ( pos_0_reg_230 );
    sensitive << ( zext_ln111_fu_572_p1 );

    SC_METHOD(thread_icmp_ln113_1_fu_610_p2);
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( icmp_ln108_fu_560_p2 );
    sensitive << ( r3_0_reg_242 );

    SC_METHOD(thread_icmp_ln113_fu_582_p2);
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( icmp_ln108_fu_560_p2 );
    sensitive << ( r3_0_reg_242 );

    SC_METHOD(thread_icmp_ln116_fu_596_p2);
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( icmp_ln108_fu_560_p2 );
    sensitive << ( pos_0_reg_230 );
    sensitive << ( zext_ln111_fu_572_p1 );

    SC_METHOD(thread_icmp_ln118_1_fu_554_p2);
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( icmp_ln102_fu_483_p2 );
    sensitive << ( trunc_ln118_fu_544_p1 );

    SC_METHOD(thread_icmp_ln118_fu_548_p2);
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( icmp_ln102_fu_483_p2 );
    sensitive << ( trunc_ln118_fu_544_p1 );

    SC_METHOD(thread_icmp_ln126_fu_870_p2);
    sensitive << ( ap_CS_fsm_state9 );
    sensitive << ( i4_0_reg_253 );

    SC_METHOD(thread_icmp_ln136_fu_906_p2);
    sensitive << ( ap_CS_fsm_state11 );
    sensitive << ( i5_0_reg_276 );

    SC_METHOD(thread_icmp_ln139_fu_928_p2);
    sensitive << ( ap_CS_fsm_state12 );
    sensitive << ( vote_list_q0 );
    sensitive << ( vote_list_q1 );

    SC_METHOD(thread_icmp_ln81_fu_324_p2);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( i_0_reg_175 );

    SC_METHOD(thread_icmp_ln88_fu_366_p2);
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( i1_0_reg_186 );

    SC_METHOD(thread_icmp_ln96_fu_415_p2);
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( label_list_2_21_reg_197 );

    SC_METHOD(thread_icmp_ln98_fu_449_p2);
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( j_0_reg_208 );

    SC_METHOD(thread_j_fu_455_p2);
    sensitive << ( j_0_reg_208 );

    SC_METHOD(thread_knn_set_address0);
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( zext_ln105_fu_470_p1 );

    SC_METHOD(thread_knn_set_ce0);
    sensitive << ( ap_CS_fsm_state5 );

    SC_METHOD(thread_label_list_0_0_load_reg_997);
    sensitive << ( ap_CS_fsm_state2 );

    SC_METHOD(thread_label_list_1_0_load_reg_1002);
    sensitive << ( ap_CS_fsm_state2 );

    SC_METHOD(thread_label_list_2_0_load_reg_1007);
    sensitive << ( ap_CS_fsm_state2 );

    SC_METHOD(thread_label_list_2_10_fu_718_p3);
    sensitive << ( icmp_ln118_1_reg_1132 );
    sensitive << ( label_list_2_2_fu_120 );
    sensitive << ( label_list_2_9_fu_712_p3 );

    SC_METHOD(thread_label_list_2_11_fu_725_p3);
    sensitive << ( zext_ln96_reg_1070 );
    sensitive << ( icmp_ln118_reg_1124 );
    sensitive << ( label_list_2_3_fu_116 );

    SC_METHOD(thread_label_list_2_12_fu_731_p3);
    sensitive << ( icmp_ln118_1_reg_1132 );
    sensitive << ( label_list_2_3_fu_116 );
    sensitive << ( label_list_2_11_fu_725_p3 );

    SC_METHOD(thread_label_list_2_13_fu_738_p3);
    sensitive << ( zext_ln96_reg_1070 );
    sensitive << ( icmp_ln118_1_reg_1132 );
    sensitive << ( label_list_2_1_fu_112 );

    SC_METHOD(thread_label_list_2_14_fu_744_p3);
    sensitive << ( label_list_2_2_fu_120 );
    sensitive << ( icmp_ln116_fu_596_p2 );
    sensitive << ( label_list_2_10_fu_718_p3 );

    SC_METHOD(thread_label_list_2_15_fu_752_p3);
    sensitive << ( label_list_2_3_fu_116 );
    sensitive << ( icmp_ln116_fu_596_p2 );
    sensitive << ( label_list_2_12_fu_731_p3 );

    SC_METHOD(thread_label_list_2_16_fu_760_p3);
    sensitive << ( label_list_2_1_fu_112 );
    sensitive << ( icmp_ln116_fu_596_p2 );
    sensitive << ( label_list_2_13_fu_738_p3 );

    SC_METHOD(thread_label_list_2_17_fu_792_p3);
    sensitive << ( icmp_ln111_fu_576_p2 );
    sensitive << ( label_list_2_5_fu_688_p3 );
    sensitive << ( label_list_2_14_fu_744_p3 );

    SC_METHOD(thread_label_list_2_18_fu_800_p3);
    sensitive << ( icmp_ln111_fu_576_p2 );
    sensitive << ( label_list_2_6_fu_696_p3 );
    sensitive << ( label_list_2_15_fu_752_p3 );

    SC_METHOD(thread_label_list_2_19_fu_808_p3);
    sensitive << ( icmp_ln111_fu_576_p2 );
    sensitive << ( label_list_2_7_fu_704_p3 );
    sensitive << ( label_list_2_16_fu_760_p3 );

    SC_METHOD(thread_label_list_2_20_fu_640_p3);
    sensitive << ( label_list_2_1_fu_112 );
    sensitive << ( label_list_2_3_fu_116 );
    sensitive << ( icmp_ln113_fu_582_p2 );

    SC_METHOD(thread_label_list_2_5_fu_688_p3);
    sensitive << ( label_list_2_2_fu_120 );
    sensitive << ( icmp_ln113_1_fu_610_p2 );
    sensitive << ( label_list_2_fu_680_p3 );

    SC_METHOD(thread_label_list_2_6_fu_696_p3);
    sensitive << ( label_list_2_3_fu_116 );
    sensitive << ( icmp_ln113_1_fu_610_p2 );
    sensitive << ( label_list_2_20_fu_640_p3 );

    SC_METHOD(thread_label_list_2_7_fu_704_p3);
    sensitive << ( label_list_2_1_fu_112 );
    sensitive << ( icmp_ln113_1_fu_610_p2 );
    sensitive << ( label_list_2_20_fu_640_p3 );

    SC_METHOD(thread_label_list_2_9_fu_712_p3);
    sensitive << ( zext_ln96_reg_1070 );
    sensitive << ( icmp_ln118_reg_1124 );
    sensitive << ( label_list_2_2_fu_120 );

    SC_METHOD(thread_label_list_2_fu_680_p3);
    sensitive << ( label_list_2_3_fu_116 );
    sensitive << ( label_list_2_2_fu_120 );
    sensitive << ( icmp_ln113_fu_582_p2 );

    SC_METHOD(thread_max_vote_fu_934_p1);
    sensitive << ( i5_0_reg_276 );

    SC_METHOD(thread_min_distance_list_0_3_reg_982);
    sensitive << ( ap_CS_fsm_state2 );

    SC_METHOD(thread_min_distance_list_1_3_reg_987);
    sensitive << ( ap_CS_fsm_state2 );

    SC_METHOD(thread_min_distance_list_2_10_fu_654_p3);
    sensitive << ( icmp_ln118_1_reg_1132 );
    sensitive << ( min_distance_list_2_2_fu_108 );
    sensitive << ( min_distance_list_2_9_fu_648_p3 );

    SC_METHOD(thread_min_distance_list_2_11_fu_661_p3);
    sensitive << ( min_distance_list_2_21_reg_1103 );
    sensitive << ( icmp_ln118_reg_1124 );
    sensitive << ( min_distance_list_2_3_fu_104 );

    SC_METHOD(thread_min_distance_list_2_12_fu_667_p3);
    sensitive << ( icmp_ln118_1_reg_1132 );
    sensitive << ( min_distance_list_2_3_fu_104 );
    sensitive << ( min_distance_list_2_11_fu_661_p3 );

    SC_METHOD(thread_min_distance_list_2_13_fu_674_p3);
    sensitive << ( min_distance_list_2_21_reg_1103 );
    sensitive << ( icmp_ln118_1_reg_1132 );
    sensitive << ( min_distance_list_2_1_fu_100 );

    SC_METHOD(thread_min_distance_list_2_14_fu_768_p3);
    sensitive << ( min_distance_list_2_2_fu_108 );
    sensitive << ( icmp_ln116_fu_596_p2 );
    sensitive << ( min_distance_list_2_10_fu_654_p3 );

    SC_METHOD(thread_min_distance_list_2_15_fu_776_p3);
    sensitive << ( min_distance_list_2_3_fu_104 );
    sensitive << ( icmp_ln116_fu_596_p2 );
    sensitive << ( min_distance_list_2_12_fu_667_p3 );

    SC_METHOD(thread_min_distance_list_2_16_fu_784_p3);
    sensitive << ( min_distance_list_2_1_fu_100 );
    sensitive << ( icmp_ln116_fu_596_p2 );
    sensitive << ( min_distance_list_2_13_fu_674_p3 );

    SC_METHOD(thread_min_distance_list_2_17_fu_816_p3);
    sensitive << ( icmp_ln111_fu_576_p2 );
    sensitive << ( min_distance_list_2_5_fu_616_p3 );
    sensitive << ( min_distance_list_2_14_fu_768_p3 );

    SC_METHOD(thread_min_distance_list_2_18_fu_824_p3);
    sensitive << ( icmp_ln111_fu_576_p2 );
    sensitive << ( min_distance_list_2_6_fu_624_p3 );
    sensitive << ( min_distance_list_2_15_fu_776_p3 );

    SC_METHOD(thread_min_distance_list_2_19_fu_832_p3);
    sensitive << ( icmp_ln111_fu_576_p2 );
    sensitive << ( min_distance_list_2_7_fu_632_p3 );
    sensitive << ( min_distance_list_2_16_fu_784_p3 );

    SC_METHOD(thread_min_distance_list_2_20_fu_588_p3);
    sensitive << ( min_distance_list_2_1_fu_100 );
    sensitive << ( min_distance_list_2_3_fu_104 );
    sensitive << ( icmp_ln113_fu_582_p2 );

    SC_METHOD(thread_min_distance_list_2_21_fu_475_p1);
    sensitive << ( knn_set_q0 );

    SC_METHOD(thread_min_distance_list_2_22_reg_992);
    sensitive << ( ap_CS_fsm_state2 );

    SC_METHOD(thread_min_distance_list_2_5_fu_616_p3);
    sensitive << ( min_distance_list_2_2_fu_108 );
    sensitive << ( icmp_ln113_1_fu_610_p2 );
    sensitive << ( min_distance_list_2_fu_602_p3 );

    SC_METHOD(thread_min_distance_list_2_6_fu_624_p3);
    sensitive << ( min_distance_list_2_3_fu_104 );
    sensitive << ( icmp_ln113_1_fu_610_p2 );
    sensitive << ( min_distance_list_2_20_fu_588_p3 );

    SC_METHOD(thread_min_distance_list_2_7_fu_632_p3);
    sensitive << ( min_distance_list_2_1_fu_100 );
    sensitive << ( icmp_ln113_1_fu_610_p2 );
    sensitive << ( min_distance_list_2_20_fu_588_p3 );

    SC_METHOD(thread_min_distance_list_2_9_fu_648_p3);
    sensitive << ( min_distance_list_2_21_reg_1103 );
    sensitive << ( icmp_ln118_reg_1124 );
    sensitive << ( min_distance_list_2_2_fu_108 );

    SC_METHOD(thread_min_distance_list_2_fu_602_p3);
    sensitive << ( min_distance_list_2_3_fu_104 );
    sensitive << ( min_distance_list_2_2_fu_108 );
    sensitive << ( icmp_ln113_fu_582_p2 );

    SC_METHOD(thread_phitmp_fu_528_p3);
    sensitive << ( pos_0_reg_230 );
    sensitive << ( icmp_ln105_1_fu_522_p2 );
    sensitive << ( zext_ln102_fu_479_p1 );

    SC_METHOD(thread_pos_fu_536_p3);
    sensitive << ( pos_0_reg_230 );
    sensitive << ( icmp_ln105_fu_507_p2 );
    sensitive << ( phitmp_fu_528_p3 );

    SC_METHOD(thread_r_1_fu_566_p2);
    sensitive << ( r3_0_reg_242 );

    SC_METHOD(thread_r_fu_489_p2);
    sensitive << ( r_0_reg_219 );

    SC_METHOD(thread_select_ln139_fu_938_p3);
    sensitive << ( max_vote_0_reg_264 );
    sensitive << ( icmp_ln139_fu_928_p2 );
    sensitive << ( max_vote_fu_934_p1 );

    SC_METHOD(thread_sext_ln105_fu_466_p1);
    sensitive << ( add_ln105_fu_461_p2 );

    SC_METHOD(thread_sext_ln129_fu_894_p1);
    sensitive << ( tmp_1_fu_882_p5 );

    SC_METHOD(thread_shl_ln_fu_427_p3);
    sensitive << ( label_list_2_21_reg_197 );

    SC_METHOD(thread_sub_ln105_fu_439_p2);
    sensitive << ( zext_ln105_1_fu_435_p1 );
    sensitive << ( zext_ln96_1_fu_411_p1 );

    SC_METHOD(thread_tmp_4_fu_512_p4);
    sensitive << ( pos_0_reg_230 );

    SC_METHOD(thread_trunc_ln118_fu_544_p1);
    sensitive << ( pos_0_reg_230 );

    SC_METHOD(thread_vote_list_address0);
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( ap_CS_fsm_state9 );
    sensitive << ( vote_list_addr_1_reg_1158 );
    sensitive << ( ap_CS_fsm_state11 );
    sensitive << ( ap_CS_fsm_state10 );
    sensitive << ( zext_ln91_fu_378_p1 );
    sensitive << ( sext_ln129_fu_894_p1 );
    sensitive << ( zext_ln139_1_fu_918_p1 );

    SC_METHOD(thread_vote_list_address1);
    sensitive << ( ap_CS_fsm_state11 );
    sensitive << ( zext_ln139_fu_923_p1 );

    SC_METHOD(thread_vote_list_ce0);
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( ap_CS_fsm_state9 );
    sensitive << ( ap_CS_fsm_state11 );
    sensitive << ( ap_CS_fsm_state10 );

    SC_METHOD(thread_vote_list_ce1);
    sensitive << ( ap_CS_fsm_state11 );

    SC_METHOD(thread_vote_list_d0);
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( ap_CS_fsm_state10 );
    sensitive << ( add_ln129_fu_899_p2 );

    SC_METHOD(thread_vote_list_we0);
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( icmp_ln88_fu_366_p2 );
    sensitive << ( ap_CS_fsm_state10 );

    SC_METHOD(thread_zext_ln102_fu_479_p1);
    sensitive << ( r_0_reg_219 );

    SC_METHOD(thread_zext_ln105_1_fu_435_p1);
    sensitive << ( shl_ln_fu_427_p3 );

    SC_METHOD(thread_zext_ln105_fu_470_p1);
    sensitive << ( sext_ln105_fu_466_p1 );

    SC_METHOD(thread_zext_ln111_fu_572_p1);
    sensitive << ( r_1_fu_566_p2 );

    SC_METHOD(thread_zext_ln139_1_fu_918_p1);
    sensitive << ( i5_0_reg_276 );

    SC_METHOD(thread_zext_ln139_fu_923_p1);
    sensitive << ( max_vote_0_reg_264 );

    SC_METHOD(thread_zext_ln91_fu_378_p1);
    sensitive << ( i1_0_reg_186 );

    SC_METHOD(thread_zext_ln96_1_fu_411_p1);
    sensitive << ( label_list_2_21_reg_197 );

    SC_METHOD(thread_zext_ln96_fu_407_p1);
    sensitive << ( label_list_2_21_reg_197 );

    SC_METHOD(thread_zext_ln98_fu_445_p1);
    sensitive << ( j_0_reg_208 );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( icmp_ln96_fu_415_p2 );
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( icmp_ln98_fu_449_p2 );
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( icmp_ln102_fu_483_p2 );
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( icmp_ln108_fu_560_p2 );
    sensitive << ( ap_CS_fsm_state9 );
    sensitive << ( icmp_ln126_fu_870_p2 );
    sensitive << ( ap_CS_fsm_state11 );
    sensitive << ( icmp_ln136_fu_906_p2 );
    sensitive << ( icmp_ln81_fu_324_p2 );
    sensitive << ( icmp_ln88_fu_366_p2 );

    ap_CS_fsm = "000000000001";
    ap_return_preg = "00000000";
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "knn_vote_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT_HIER__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, knn_set_address0, "(port)knn_set_address0");
    sc_trace(mVcdFile, knn_set_ce0, "(port)knn_set_ce0");
    sc_trace(mVcdFile, knn_set_q0, "(port)knn_set_q0");
    sc_trace(mVcdFile, ap_return, "(port)ap_return");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_CS_fsm_state1, "ap_CS_fsm_state1");
    sc_trace(mVcdFile, min_distance_list_0_3_reg_982, "min_distance_list_0_3_reg_982");
    sc_trace(mVcdFile, ap_CS_fsm_state2, "ap_CS_fsm_state2");
    sc_trace(mVcdFile, min_distance_list_1_3_reg_987, "min_distance_list_1_3_reg_987");
    sc_trace(mVcdFile, min_distance_list_2_22_reg_992, "min_distance_list_2_22_reg_992");
    sc_trace(mVcdFile, label_list_0_0_load_reg_997, "label_list_0_0_load_reg_997");
    sc_trace(mVcdFile, label_list_1_0_load_reg_1002, "label_list_1_0_load_reg_1002");
    sc_trace(mVcdFile, label_list_2_0_load_reg_1007, "label_list_2_0_load_reg_1007");
    sc_trace(mVcdFile, i_fu_330_p2, "i_fu_330_p2");
    sc_trace(mVcdFile, i_1_fu_372_p2, "i_1_fu_372_p2");
    sc_trace(mVcdFile, ap_CS_fsm_state3, "ap_CS_fsm_state3");
    sc_trace(mVcdFile, zext_ln96_fu_407_p1, "zext_ln96_fu_407_p1");
    sc_trace(mVcdFile, zext_ln96_reg_1070, "zext_ln96_reg_1070");
    sc_trace(mVcdFile, ap_CS_fsm_state4, "ap_CS_fsm_state4");
    sc_trace(mVcdFile, i_3_fu_421_p2, "i_3_fu_421_p2");
    sc_trace(mVcdFile, i_3_reg_1080, "i_3_reg_1080");
    sc_trace(mVcdFile, sub_ln105_fu_439_p2, "sub_ln105_fu_439_p2");
    sc_trace(mVcdFile, sub_ln105_reg_1085, "sub_ln105_reg_1085");
    sc_trace(mVcdFile, icmp_ln96_fu_415_p2, "icmp_ln96_fu_415_p2");
    sc_trace(mVcdFile, j_fu_455_p2, "j_fu_455_p2");
    sc_trace(mVcdFile, j_reg_1093, "j_reg_1093");
    sc_trace(mVcdFile, ap_CS_fsm_state5, "ap_CS_fsm_state5");
    sc_trace(mVcdFile, icmp_ln98_fu_449_p2, "icmp_ln98_fu_449_p2");
    sc_trace(mVcdFile, min_distance_list_2_21_fu_475_p1, "min_distance_list_2_21_fu_475_p1");
    sc_trace(mVcdFile, min_distance_list_2_21_reg_1103, "min_distance_list_2_21_reg_1103");
    sc_trace(mVcdFile, ap_CS_fsm_state6, "ap_CS_fsm_state6");
    sc_trace(mVcdFile, r_fu_489_p2, "r_fu_489_p2");
    sc_trace(mVcdFile, ap_CS_fsm_state7, "ap_CS_fsm_state7");
    sc_trace(mVcdFile, pos_fu_536_p3, "pos_fu_536_p3");
    sc_trace(mVcdFile, icmp_ln102_fu_483_p2, "icmp_ln102_fu_483_p2");
    sc_trace(mVcdFile, icmp_ln118_fu_548_p2, "icmp_ln118_fu_548_p2");
    sc_trace(mVcdFile, icmp_ln118_reg_1124, "icmp_ln118_reg_1124");
    sc_trace(mVcdFile, icmp_ln118_1_fu_554_p2, "icmp_ln118_1_fu_554_p2");
    sc_trace(mVcdFile, icmp_ln118_1_reg_1132, "icmp_ln118_1_reg_1132");
    sc_trace(mVcdFile, r_1_fu_566_p2, "r_1_fu_566_p2");
    sc_trace(mVcdFile, ap_CS_fsm_state8, "ap_CS_fsm_state8");
    sc_trace(mVcdFile, icmp_ln108_fu_560_p2, "icmp_ln108_fu_560_p2");
    sc_trace(mVcdFile, i_2_fu_876_p2, "i_2_fu_876_p2");
    sc_trace(mVcdFile, i_2_reg_1153, "i_2_reg_1153");
    sc_trace(mVcdFile, ap_CS_fsm_state9, "ap_CS_fsm_state9");
    sc_trace(mVcdFile, vote_list_addr_1_reg_1158, "vote_list_addr_1_reg_1158");
    sc_trace(mVcdFile, icmp_ln126_fu_870_p2, "icmp_ln126_fu_870_p2");
    sc_trace(mVcdFile, i_4_fu_912_p2, "i_4_fu_912_p2");
    sc_trace(mVcdFile, i_4_reg_1166, "i_4_reg_1166");
    sc_trace(mVcdFile, ap_CS_fsm_state11, "ap_CS_fsm_state11");
    sc_trace(mVcdFile, icmp_ln136_fu_906_p2, "icmp_ln136_fu_906_p2");
    sc_trace(mVcdFile, select_ln139_fu_938_p3, "select_ln139_fu_938_p3");
    sc_trace(mVcdFile, ap_CS_fsm_state12, "ap_CS_fsm_state12");
    sc_trace(mVcdFile, vote_list_address0, "vote_list_address0");
    sc_trace(mVcdFile, vote_list_ce0, "vote_list_ce0");
    sc_trace(mVcdFile, vote_list_we0, "vote_list_we0");
    sc_trace(mVcdFile, vote_list_d0, "vote_list_d0");
    sc_trace(mVcdFile, vote_list_q0, "vote_list_q0");
    sc_trace(mVcdFile, vote_list_address1, "vote_list_address1");
    sc_trace(mVcdFile, vote_list_ce1, "vote_list_ce1");
    sc_trace(mVcdFile, vote_list_q1, "vote_list_q1");
    sc_trace(mVcdFile, i_0_reg_175, "i_0_reg_175");
    sc_trace(mVcdFile, icmp_ln81_fu_324_p2, "icmp_ln81_fu_324_p2");
    sc_trace(mVcdFile, i1_0_reg_186, "i1_0_reg_186");
    sc_trace(mVcdFile, icmp_ln88_fu_366_p2, "icmp_ln88_fu_366_p2");
    sc_trace(mVcdFile, label_list_2_21_reg_197, "label_list_2_21_reg_197");
    sc_trace(mVcdFile, j_0_reg_208, "j_0_reg_208");
    sc_trace(mVcdFile, r_0_reg_219, "r_0_reg_219");
    sc_trace(mVcdFile, pos_0_reg_230, "pos_0_reg_230");
    sc_trace(mVcdFile, r3_0_reg_242, "r3_0_reg_242");
    sc_trace(mVcdFile, i4_0_reg_253, "i4_0_reg_253");
    sc_trace(mVcdFile, ap_CS_fsm_state10, "ap_CS_fsm_state10");
    sc_trace(mVcdFile, max_vote_0_reg_264, "max_vote_0_reg_264");
    sc_trace(mVcdFile, i5_0_reg_276, "i5_0_reg_276");
    sc_trace(mVcdFile, zext_ln91_fu_378_p1, "zext_ln91_fu_378_p1");
    sc_trace(mVcdFile, zext_ln105_fu_470_p1, "zext_ln105_fu_470_p1");
    sc_trace(mVcdFile, sext_ln129_fu_894_p1, "sext_ln129_fu_894_p1");
    sc_trace(mVcdFile, zext_ln139_1_fu_918_p1, "zext_ln139_1_fu_918_p1");
    sc_trace(mVcdFile, zext_ln139_fu_923_p1, "zext_ln139_fu_923_p1");
    sc_trace(mVcdFile, min_distance_list_2_1_fu_100, "min_distance_list_2_1_fu_100");
    sc_trace(mVcdFile, min_distance_list_2_19_fu_832_p3, "min_distance_list_2_19_fu_832_p3");
    sc_trace(mVcdFile, min_distance_list_2_3_fu_104, "min_distance_list_2_3_fu_104");
    sc_trace(mVcdFile, min_distance_list_2_18_fu_824_p3, "min_distance_list_2_18_fu_824_p3");
    sc_trace(mVcdFile, min_distance_list_2_2_fu_108, "min_distance_list_2_2_fu_108");
    sc_trace(mVcdFile, min_distance_list_2_17_fu_816_p3, "min_distance_list_2_17_fu_816_p3");
    sc_trace(mVcdFile, label_list_2_1_fu_112, "label_list_2_1_fu_112");
    sc_trace(mVcdFile, label_list_2_19_fu_808_p3, "label_list_2_19_fu_808_p3");
    sc_trace(mVcdFile, label_list_2_3_fu_116, "label_list_2_3_fu_116");
    sc_trace(mVcdFile, label_list_2_18_fu_800_p3, "label_list_2_18_fu_800_p3");
    sc_trace(mVcdFile, label_list_2_2_fu_120, "label_list_2_2_fu_120");
    sc_trace(mVcdFile, label_list_2_17_fu_792_p3, "label_list_2_17_fu_792_p3");
    sc_trace(mVcdFile, add_ln129_fu_899_p2, "add_ln129_fu_899_p2");
    sc_trace(mVcdFile, shl_ln_fu_427_p3, "shl_ln_fu_427_p3");
    sc_trace(mVcdFile, zext_ln105_1_fu_435_p1, "zext_ln105_1_fu_435_p1");
    sc_trace(mVcdFile, zext_ln96_1_fu_411_p1, "zext_ln96_1_fu_411_p1");
    sc_trace(mVcdFile, zext_ln98_fu_445_p1, "zext_ln98_fu_445_p1");
    sc_trace(mVcdFile, add_ln105_fu_461_p2, "add_ln105_fu_461_p2");
    sc_trace(mVcdFile, sext_ln105_fu_466_p1, "sext_ln105_fu_466_p1");
    sc_trace(mVcdFile, tmp_3_fu_495_p5, "tmp_3_fu_495_p5");
    sc_trace(mVcdFile, tmp_4_fu_512_p4, "tmp_4_fu_512_p4");
    sc_trace(mVcdFile, icmp_ln105_1_fu_522_p2, "icmp_ln105_1_fu_522_p2");
    sc_trace(mVcdFile, zext_ln102_fu_479_p1, "zext_ln102_fu_479_p1");
    sc_trace(mVcdFile, icmp_ln105_fu_507_p2, "icmp_ln105_fu_507_p2");
    sc_trace(mVcdFile, phitmp_fu_528_p3, "phitmp_fu_528_p3");
    sc_trace(mVcdFile, trunc_ln118_fu_544_p1, "trunc_ln118_fu_544_p1");
    sc_trace(mVcdFile, zext_ln111_fu_572_p1, "zext_ln111_fu_572_p1");
    sc_trace(mVcdFile, icmp_ln113_fu_582_p2, "icmp_ln113_fu_582_p2");
    sc_trace(mVcdFile, icmp_ln113_1_fu_610_p2, "icmp_ln113_1_fu_610_p2");
    sc_trace(mVcdFile, min_distance_list_2_fu_602_p3, "min_distance_list_2_fu_602_p3");
    sc_trace(mVcdFile, min_distance_list_2_20_fu_588_p3, "min_distance_list_2_20_fu_588_p3");
    sc_trace(mVcdFile, min_distance_list_2_9_fu_648_p3, "min_distance_list_2_9_fu_648_p3");
    sc_trace(mVcdFile, min_distance_list_2_11_fu_661_p3, "min_distance_list_2_11_fu_661_p3");
    sc_trace(mVcdFile, label_list_2_fu_680_p3, "label_list_2_fu_680_p3");
    sc_trace(mVcdFile, label_list_2_20_fu_640_p3, "label_list_2_20_fu_640_p3");
    sc_trace(mVcdFile, label_list_2_9_fu_712_p3, "label_list_2_9_fu_712_p3");
    sc_trace(mVcdFile, label_list_2_11_fu_725_p3, "label_list_2_11_fu_725_p3");
    sc_trace(mVcdFile, icmp_ln116_fu_596_p2, "icmp_ln116_fu_596_p2");
    sc_trace(mVcdFile, label_list_2_10_fu_718_p3, "label_list_2_10_fu_718_p3");
    sc_trace(mVcdFile, label_list_2_12_fu_731_p3, "label_list_2_12_fu_731_p3");
    sc_trace(mVcdFile, label_list_2_13_fu_738_p3, "label_list_2_13_fu_738_p3");
    sc_trace(mVcdFile, min_distance_list_2_10_fu_654_p3, "min_distance_list_2_10_fu_654_p3");
    sc_trace(mVcdFile, min_distance_list_2_12_fu_667_p3, "min_distance_list_2_12_fu_667_p3");
    sc_trace(mVcdFile, min_distance_list_2_13_fu_674_p3, "min_distance_list_2_13_fu_674_p3");
    sc_trace(mVcdFile, icmp_ln111_fu_576_p2, "icmp_ln111_fu_576_p2");
    sc_trace(mVcdFile, label_list_2_5_fu_688_p3, "label_list_2_5_fu_688_p3");
    sc_trace(mVcdFile, label_list_2_14_fu_744_p3, "label_list_2_14_fu_744_p3");
    sc_trace(mVcdFile, label_list_2_6_fu_696_p3, "label_list_2_6_fu_696_p3");
    sc_trace(mVcdFile, label_list_2_15_fu_752_p3, "label_list_2_15_fu_752_p3");
    sc_trace(mVcdFile, label_list_2_7_fu_704_p3, "label_list_2_7_fu_704_p3");
    sc_trace(mVcdFile, label_list_2_16_fu_760_p3, "label_list_2_16_fu_760_p3");
    sc_trace(mVcdFile, min_distance_list_2_5_fu_616_p3, "min_distance_list_2_5_fu_616_p3");
    sc_trace(mVcdFile, min_distance_list_2_14_fu_768_p3, "min_distance_list_2_14_fu_768_p3");
    sc_trace(mVcdFile, min_distance_list_2_6_fu_624_p3, "min_distance_list_2_6_fu_624_p3");
    sc_trace(mVcdFile, min_distance_list_2_15_fu_776_p3, "min_distance_list_2_15_fu_776_p3");
    sc_trace(mVcdFile, min_distance_list_2_7_fu_632_p3, "min_distance_list_2_7_fu_632_p3");
    sc_trace(mVcdFile, min_distance_list_2_16_fu_784_p3, "min_distance_list_2_16_fu_784_p3");
    sc_trace(mVcdFile, tmp_1_fu_882_p5, "tmp_1_fu_882_p5");
    sc_trace(mVcdFile, icmp_ln139_fu_928_p2, "icmp_ln139_fu_928_p2");
    sc_trace(mVcdFile, max_vote_fu_934_p1, "max_vote_fu_934_p1");
    sc_trace(mVcdFile, ap_return_preg, "ap_return_preg");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
#endif

    }
}

knn_vote::~knn_vote() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    delete vote_list_U;
    delete DigitRec_mux_32_3bkb_U1;
    delete DigitRec_mux_32_3bkb_U2;
}

void knn_vote::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_fsm_state1;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_return_preg = ap_const_lv8_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state11.read()) && 
             esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln136_fu_906_p2.read()))) {
            ap_return_preg = max_vote_0_reg_264.read();
        }
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln81_fu_324_p2.read()))) {
        i1_0_reg_186 = ap_const_lv4_0;
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln88_fu_366_p2.read()))) {
        i1_0_reg_186 = i_1_fu_372_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && 
         esl_seteq<1,1,1>(icmp_ln96_fu_415_p2.read(), ap_const_lv1_1))) {
        i4_0_reg_253 = ap_const_lv2_0;
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read())) {
        i4_0_reg_253 = i_2_reg_1153.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln126_fu_870_p2.read()))) {
        i5_0_reg_276 = ap_const_lv4_0;
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state12.read())) {
        i5_0_reg_276 = i_4_reg_1166.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln81_fu_324_p2.read()))) {
        i_0_reg_175 = i_fu_330_p2.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
        i_0_reg_175 = ap_const_lv2_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln108_fu_560_p2.read()))) {
        j_0_reg_208 = j_reg_1093.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && 
                esl_seteq<1,1,1>(icmp_ln96_fu_415_p2.read(), ap_const_lv1_0))) {
        j_0_reg_208 = ap_const_lv2_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln108_fu_560_p2.read()))) {
        label_list_2_1_fu_112 = label_list_2_19_fu_808_p3.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln88_fu_366_p2.read()))) {
        label_list_2_1_fu_112 = label_list_0_0_load_reg_997.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln88_fu_366_p2.read()))) {
        label_list_2_21_reg_197 = ap_const_lv4_0;
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) && 
                esl_seteq<1,1,1>(icmp_ln98_fu_449_p2.read(), ap_const_lv1_1))) {
        label_list_2_21_reg_197 = i_3_reg_1080.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln108_fu_560_p2.read()))) {
        label_list_2_2_fu_120 = label_list_2_17_fu_792_p3.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln88_fu_366_p2.read()))) {
        label_list_2_2_fu_120 = label_list_2_0_load_reg_1007.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln108_fu_560_p2.read()))) {
        label_list_2_3_fu_116 = label_list_2_18_fu_800_p3.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln88_fu_366_p2.read()))) {
        label_list_2_3_fu_116 = label_list_1_0_load_reg_1002.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln126_fu_870_p2.read()))) {
        max_vote_0_reg_264 = ap_const_lv8_0;
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state12.read())) {
        max_vote_0_reg_264 = select_ln139_fu_938_p3.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln108_fu_560_p2.read()))) {
        min_distance_list_2_1_fu_100 = min_distance_list_2_19_fu_832_p3.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln88_fu_366_p2.read()))) {
        min_distance_list_2_1_fu_100 = min_distance_list_0_3_reg_982.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln108_fu_560_p2.read()))) {
        min_distance_list_2_2_fu_108 = min_distance_list_2_17_fu_816_p3.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln88_fu_366_p2.read()))) {
        min_distance_list_2_2_fu_108 = min_distance_list_2_22_reg_992.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln108_fu_560_p2.read()))) {
        min_distance_list_2_3_fu_104 = min_distance_list_2_18_fu_824_p3.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln88_fu_366_p2.read()))) {
        min_distance_list_2_3_fu_104 = min_distance_list_1_3_reg_987.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln102_fu_483_p2.read()))) {
        pos_0_reg_230 = pos_fu_536_p3.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
        pos_0_reg_230 = ap_const_lv32_3E8;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln108_fu_560_p2.read()))) {
        r3_0_reg_242 = r_1_fu_566_p2.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) && 
                esl_seteq<1,1,1>(icmp_ln102_fu_483_p2.read(), ap_const_lv1_1))) {
        r3_0_reg_242 = ap_const_lv2_3;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln102_fu_483_p2.read()))) {
        r_0_reg_219 = r_fu_489_p2.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
        r_0_reg_219 = ap_const_lv2_0;
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read())) {
        i_2_reg_1153 = i_2_fu_876_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        i_3_reg_1080 = i_3_fu_421_p2.read();
        zext_ln96_reg_1070 = zext_ln96_fu_407_p1.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state11.read())) {
        i_4_reg_1166 = i_4_fu_912_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) && esl_seteq<1,1,1>(icmp_ln102_fu_483_p2.read(), ap_const_lv1_1))) {
        icmp_ln118_1_reg_1132 = icmp_ln118_1_fu_554_p2.read();
        icmp_ln118_reg_1124 = icmp_ln118_fu_548_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read())) {
        j_reg_1093 = j_fu_455_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
        min_distance_list_2_21_reg_1103 = min_distance_list_2_21_fu_475_p1.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && esl_seteq<1,1,1>(icmp_ln96_fu_415_p2.read(), ap_const_lv1_0))) {
        sub_ln105_reg_1085 = sub_ln105_fu_439_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln126_fu_870_p2.read()))) {
        vote_list_addr_1_reg_1158 =  (sc_lv<4>) (sext_ln129_fu_894_p1.read());
    }
}

void knn_vote::thread_add_ln105_fu_461_p2() {
    add_ln105_fu_461_p2 = (!sub_ln105_reg_1085.read().is_01() || !zext_ln98_fu_445_p1.read().is_01())? sc_lv<7>(): (sc_biguint<7>(sub_ln105_reg_1085.read()) + sc_biguint<7>(zext_ln98_fu_445_p1.read()));
}

void knn_vote::thread_add_ln129_fu_899_p2() {
    add_ln129_fu_899_p2 = (!vote_list_q0.read().is_01() || !ap_const_lv32_1.is_01())? sc_lv<32>(): (sc_biguint<32>(vote_list_q0.read()) + sc_biguint<32>(ap_const_lv32_1));
}

void knn_vote::thread_ap_CS_fsm_state1() {
    ap_CS_fsm_state1 = ap_CS_fsm.read()[0];
}

void knn_vote::thread_ap_CS_fsm_state10() {
    ap_CS_fsm_state10 = ap_CS_fsm.read()[9];
}

void knn_vote::thread_ap_CS_fsm_state11() {
    ap_CS_fsm_state11 = ap_CS_fsm.read()[10];
}

void knn_vote::thread_ap_CS_fsm_state12() {
    ap_CS_fsm_state12 = ap_CS_fsm.read()[11];
}

void knn_vote::thread_ap_CS_fsm_state2() {
    ap_CS_fsm_state2 = ap_CS_fsm.read()[1];
}

void knn_vote::thread_ap_CS_fsm_state3() {
    ap_CS_fsm_state3 = ap_CS_fsm.read()[2];
}

void knn_vote::thread_ap_CS_fsm_state4() {
    ap_CS_fsm_state4 = ap_CS_fsm.read()[3];
}

void knn_vote::thread_ap_CS_fsm_state5() {
    ap_CS_fsm_state5 = ap_CS_fsm.read()[4];
}

void knn_vote::thread_ap_CS_fsm_state6() {
    ap_CS_fsm_state6 = ap_CS_fsm.read()[5];
}

void knn_vote::thread_ap_CS_fsm_state7() {
    ap_CS_fsm_state7 = ap_CS_fsm.read()[6];
}

void knn_vote::thread_ap_CS_fsm_state8() {
    ap_CS_fsm_state8 = ap_CS_fsm.read()[7];
}

void knn_vote::thread_ap_CS_fsm_state9() {
    ap_CS_fsm_state9 = ap_CS_fsm.read()[8];
}

void knn_vote::thread_ap_done() {
    if (((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read())) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state11.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln136_fu_906_p2.read())))) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_const_logic_0;
    }
}

void knn_vote::thread_ap_idle() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void knn_vote::thread_ap_ready() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state11.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln136_fu_906_p2.read()))) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void knn_vote::thread_ap_return() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state11.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln136_fu_906_p2.read()))) {
        ap_return = max_vote_0_reg_264.read();
    } else {
        ap_return = ap_return_preg.read();
    }
}

void knn_vote::thread_i_1_fu_372_p2() {
    i_1_fu_372_p2 = (!i1_0_reg_186.read().is_01() || !ap_const_lv4_1.is_01())? sc_lv<4>(): (sc_biguint<4>(i1_0_reg_186.read()) + sc_biguint<4>(ap_const_lv4_1));
}

void knn_vote::thread_i_2_fu_876_p2() {
    i_2_fu_876_p2 = (!i4_0_reg_253.read().is_01() || !ap_const_lv2_1.is_01())? sc_lv<2>(): (sc_biguint<2>(i4_0_reg_253.read()) + sc_biguint<2>(ap_const_lv2_1));
}

void knn_vote::thread_i_3_fu_421_p2() {
    i_3_fu_421_p2 = (!label_list_2_21_reg_197.read().is_01() || !ap_const_lv4_1.is_01())? sc_lv<4>(): (sc_biguint<4>(label_list_2_21_reg_197.read()) + sc_biguint<4>(ap_const_lv4_1));
}

void knn_vote::thread_i_4_fu_912_p2() {
    i_4_fu_912_p2 = (!i5_0_reg_276.read().is_01() || !ap_const_lv4_1.is_01())? sc_lv<4>(): (sc_biguint<4>(i5_0_reg_276.read()) + sc_biguint<4>(ap_const_lv4_1));
}

void knn_vote::thread_i_fu_330_p2() {
    i_fu_330_p2 = (!i_0_reg_175.read().is_01() || !ap_const_lv2_1.is_01())? sc_lv<2>(): (sc_biguint<2>(i_0_reg_175.read()) + sc_biguint<2>(ap_const_lv2_1));
}

void knn_vote::thread_icmp_ln102_fu_483_p2() {
    icmp_ln102_fu_483_p2 = (!r_0_reg_219.read().is_01() || !ap_const_lv2_3.is_01())? sc_lv<1>(): sc_lv<1>(r_0_reg_219.read() == ap_const_lv2_3);
}

void knn_vote::thread_icmp_ln105_1_fu_522_p2() {
    icmp_ln105_1_fu_522_p2 = (!tmp_4_fu_512_p4.read().is_01() || !ap_const_lv30_0.is_01())? sc_lv<1>(): (sc_bigint<30>(tmp_4_fu_512_p4.read()) > sc_bigint<30>(ap_const_lv30_0));
}

void knn_vote::thread_icmp_ln105_fu_507_p2() {
    icmp_ln105_fu_507_p2 = (!min_distance_list_2_21_reg_1103.read().is_01() || !tmp_3_fu_495_p5.read().is_01())? sc_lv<1>(): (sc_bigint<32>(min_distance_list_2_21_reg_1103.read()) < sc_bigint<32>(tmp_3_fu_495_p5.read()));
}

void knn_vote::thread_icmp_ln108_fu_560_p2() {
    icmp_ln108_fu_560_p2 = (!r3_0_reg_242.read().is_01() || !ap_const_lv2_0.is_01())? sc_lv<1>(): sc_lv<1>(r3_0_reg_242.read() == ap_const_lv2_0);
}

void knn_vote::thread_icmp_ln111_fu_576_p2() {
    icmp_ln111_fu_576_p2 = (!zext_ln111_fu_572_p1.read().is_01() || !pos_0_reg_230.read().is_01())? sc_lv<1>(): (sc_bigint<32>(zext_ln111_fu_572_p1.read()) > sc_bigint<32>(pos_0_reg_230.read()));
}

void knn_vote::thread_icmp_ln113_1_fu_610_p2() {
    icmp_ln113_1_fu_610_p2 = (!r3_0_reg_242.read().is_01() || !ap_const_lv2_1.is_01())? sc_lv<1>(): sc_lv<1>(r3_0_reg_242.read() == ap_const_lv2_1);
}

void knn_vote::thread_icmp_ln113_fu_582_p2() {
    icmp_ln113_fu_582_p2 = (!r3_0_reg_242.read().is_01() || !ap_const_lv2_2.is_01())? sc_lv<1>(): sc_lv<1>(r3_0_reg_242.read() == ap_const_lv2_2);
}

void knn_vote::thread_icmp_ln116_fu_596_p2() {
    icmp_ln116_fu_596_p2 = (!zext_ln111_fu_572_p1.read().is_01() || !pos_0_reg_230.read().is_01())? sc_lv<1>(): sc_lv<1>(zext_ln111_fu_572_p1.read() == pos_0_reg_230.read());
}

void knn_vote::thread_icmp_ln118_1_fu_554_p2() {
    icmp_ln118_1_fu_554_p2 = (!trunc_ln118_fu_544_p1.read().is_01() || !ap_const_lv2_0.is_01())? sc_lv<1>(): sc_lv<1>(trunc_ln118_fu_544_p1.read() == ap_const_lv2_0);
}

void knn_vote::thread_icmp_ln118_fu_548_p2() {
    icmp_ln118_fu_548_p2 = (!trunc_ln118_fu_544_p1.read().is_01() || !ap_const_lv2_1.is_01())? sc_lv<1>(): sc_lv<1>(trunc_ln118_fu_544_p1.read() == ap_const_lv2_1);
}

void knn_vote::thread_icmp_ln126_fu_870_p2() {
    icmp_ln126_fu_870_p2 = (!i4_0_reg_253.read().is_01() || !ap_const_lv2_3.is_01())? sc_lv<1>(): sc_lv<1>(i4_0_reg_253.read() == ap_const_lv2_3);
}

void knn_vote::thread_icmp_ln136_fu_906_p2() {
    icmp_ln136_fu_906_p2 = (!i5_0_reg_276.read().is_01() || !ap_const_lv4_A.is_01())? sc_lv<1>(): sc_lv<1>(i5_0_reg_276.read() == ap_const_lv4_A);
}

void knn_vote::thread_icmp_ln139_fu_928_p2() {
    icmp_ln139_fu_928_p2 = (!vote_list_q0.read().is_01() || !vote_list_q1.read().is_01())? sc_lv<1>(): (sc_bigint<32>(vote_list_q0.read()) < sc_bigint<32>(vote_list_q1.read()));
}

void knn_vote::thread_icmp_ln81_fu_324_p2() {
    icmp_ln81_fu_324_p2 = (!i_0_reg_175.read().is_01() || !ap_const_lv2_3.is_01())? sc_lv<1>(): sc_lv<1>(i_0_reg_175.read() == ap_const_lv2_3);
}

void knn_vote::thread_icmp_ln88_fu_366_p2() {
    icmp_ln88_fu_366_p2 = (!i1_0_reg_186.read().is_01() || !ap_const_lv4_A.is_01())? sc_lv<1>(): sc_lv<1>(i1_0_reg_186.read() == ap_const_lv4_A);
}

void knn_vote::thread_icmp_ln96_fu_415_p2() {
    icmp_ln96_fu_415_p2 = (!label_list_2_21_reg_197.read().is_01() || !ap_const_lv4_A.is_01())? sc_lv<1>(): sc_lv<1>(label_list_2_21_reg_197.read() == ap_const_lv4_A);
}

void knn_vote::thread_icmp_ln98_fu_449_p2() {
    icmp_ln98_fu_449_p2 = (!j_0_reg_208.read().is_01() || !ap_const_lv2_3.is_01())? sc_lv<1>(): sc_lv<1>(j_0_reg_208.read() == ap_const_lv2_3);
}

void knn_vote::thread_j_fu_455_p2() {
    j_fu_455_p2 = (!j_0_reg_208.read().is_01() || !ap_const_lv2_1.is_01())? sc_lv<2>(): (sc_biguint<2>(j_0_reg_208.read()) + sc_biguint<2>(ap_const_lv2_1));
}

void knn_vote::thread_knn_set_address0() {
    knn_set_address0 =  (sc_lv<5>) (zext_ln105_fu_470_p1.read());
}

void knn_vote::thread_knn_set_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read())) {
        knn_set_ce0 = ap_const_logic_1;
    } else {
        knn_set_ce0 = ap_const_logic_0;
    }
}

void knn_vote::thread_label_list_0_0_load_reg_997() {
    label_list_0_0_load_reg_997 = ap_const_lv32_9;
}

void knn_vote::thread_label_list_1_0_load_reg_1002() {
    label_list_1_0_load_reg_1002 = ap_const_lv32_9;
}

void knn_vote::thread_label_list_2_0_load_reg_1007() {
    label_list_2_0_load_reg_1007 = ap_const_lv32_9;
}

void knn_vote::thread_label_list_2_10_fu_718_p3() {
    label_list_2_10_fu_718_p3 = (!icmp_ln118_1_reg_1132.read()[0].is_01())? sc_lv<32>(): ((icmp_ln118_1_reg_1132.read()[0].to_bool())? label_list_2_2_fu_120.read(): label_list_2_9_fu_712_p3.read());
}

void knn_vote::thread_label_list_2_11_fu_725_p3() {
    label_list_2_11_fu_725_p3 = (!icmp_ln118_reg_1124.read()[0].is_01())? sc_lv<32>(): ((icmp_ln118_reg_1124.read()[0].to_bool())? zext_ln96_reg_1070.read(): label_list_2_3_fu_116.read());
}

void knn_vote::thread_label_list_2_12_fu_731_p3() {
    label_list_2_12_fu_731_p3 = (!icmp_ln118_1_reg_1132.read()[0].is_01())? sc_lv<32>(): ((icmp_ln118_1_reg_1132.read()[0].to_bool())? label_list_2_3_fu_116.read(): label_list_2_11_fu_725_p3.read());
}

void knn_vote::thread_label_list_2_13_fu_738_p3() {
    label_list_2_13_fu_738_p3 = (!icmp_ln118_1_reg_1132.read()[0].is_01())? sc_lv<32>(): ((icmp_ln118_1_reg_1132.read()[0].to_bool())? zext_ln96_reg_1070.read(): label_list_2_1_fu_112.read());
}

void knn_vote::thread_label_list_2_14_fu_744_p3() {
    label_list_2_14_fu_744_p3 = (!icmp_ln116_fu_596_p2.read()[0].is_01())? sc_lv<32>(): ((icmp_ln116_fu_596_p2.read()[0].to_bool())? label_list_2_10_fu_718_p3.read(): label_list_2_2_fu_120.read());
}

void knn_vote::thread_label_list_2_15_fu_752_p3() {
    label_list_2_15_fu_752_p3 = (!icmp_ln116_fu_596_p2.read()[0].is_01())? sc_lv<32>(): ((icmp_ln116_fu_596_p2.read()[0].to_bool())? label_list_2_12_fu_731_p3.read(): label_list_2_3_fu_116.read());
}

void knn_vote::thread_label_list_2_16_fu_760_p3() {
    label_list_2_16_fu_760_p3 = (!icmp_ln116_fu_596_p2.read()[0].is_01())? sc_lv<32>(): ((icmp_ln116_fu_596_p2.read()[0].to_bool())? label_list_2_13_fu_738_p3.read(): label_list_2_1_fu_112.read());
}

void knn_vote::thread_label_list_2_17_fu_792_p3() {
    label_list_2_17_fu_792_p3 = (!icmp_ln111_fu_576_p2.read()[0].is_01())? sc_lv<32>(): ((icmp_ln111_fu_576_p2.read()[0].to_bool())? label_list_2_5_fu_688_p3.read(): label_list_2_14_fu_744_p3.read());
}

void knn_vote::thread_label_list_2_18_fu_800_p3() {
    label_list_2_18_fu_800_p3 = (!icmp_ln111_fu_576_p2.read()[0].is_01())? sc_lv<32>(): ((icmp_ln111_fu_576_p2.read()[0].to_bool())? label_list_2_6_fu_696_p3.read(): label_list_2_15_fu_752_p3.read());
}

void knn_vote::thread_label_list_2_19_fu_808_p3() {
    label_list_2_19_fu_808_p3 = (!icmp_ln111_fu_576_p2.read()[0].is_01())? sc_lv<32>(): ((icmp_ln111_fu_576_p2.read()[0].to_bool())? label_list_2_7_fu_704_p3.read(): label_list_2_16_fu_760_p3.read());
}

void knn_vote::thread_label_list_2_20_fu_640_p3() {
    label_list_2_20_fu_640_p3 = (!icmp_ln113_fu_582_p2.read()[0].is_01())? sc_lv<32>(): ((icmp_ln113_fu_582_p2.read()[0].to_bool())? label_list_2_1_fu_112.read(): label_list_2_3_fu_116.read());
}

void knn_vote::thread_label_list_2_5_fu_688_p3() {
    label_list_2_5_fu_688_p3 = (!icmp_ln113_1_fu_610_p2.read()[0].is_01())? sc_lv<32>(): ((icmp_ln113_1_fu_610_p2.read()[0].to_bool())? label_list_2_2_fu_120.read(): label_list_2_fu_680_p3.read());
}

void knn_vote::thread_label_list_2_6_fu_696_p3() {
    label_list_2_6_fu_696_p3 = (!icmp_ln113_1_fu_610_p2.read()[0].is_01())? sc_lv<32>(): ((icmp_ln113_1_fu_610_p2.read()[0].to_bool())? label_list_2_3_fu_116.read(): label_list_2_20_fu_640_p3.read());
}

void knn_vote::thread_label_list_2_7_fu_704_p3() {
    label_list_2_7_fu_704_p3 = (!icmp_ln113_1_fu_610_p2.read()[0].is_01())? sc_lv<32>(): ((icmp_ln113_1_fu_610_p2.read()[0].to_bool())? label_list_2_20_fu_640_p3.read(): label_list_2_1_fu_112.read());
}

void knn_vote::thread_label_list_2_9_fu_712_p3() {
    label_list_2_9_fu_712_p3 = (!icmp_ln118_reg_1124.read()[0].is_01())? sc_lv<32>(): ((icmp_ln118_reg_1124.read()[0].to_bool())? label_list_2_2_fu_120.read(): zext_ln96_reg_1070.read());
}

void knn_vote::thread_label_list_2_fu_680_p3() {
    label_list_2_fu_680_p3 = (!icmp_ln113_fu_582_p2.read()[0].is_01())? sc_lv<32>(): ((icmp_ln113_fu_582_p2.read()[0].to_bool())? label_list_2_2_fu_120.read(): label_list_2_3_fu_116.read());
}

void knn_vote::thread_max_vote_fu_934_p1() {
    max_vote_fu_934_p1 = esl_zext<8,4>(i5_0_reg_276.read());
}

void knn_vote::thread_min_distance_list_0_3_reg_982() {
    min_distance_list_0_3_reg_982 = ap_const_lv32_100;
}

void knn_vote::thread_min_distance_list_1_3_reg_987() {
    min_distance_list_1_3_reg_987 = ap_const_lv32_100;
}

void knn_vote::thread_min_distance_list_2_10_fu_654_p3() {
    min_distance_list_2_10_fu_654_p3 = (!icmp_ln118_1_reg_1132.read()[0].is_01())? sc_lv<32>(): ((icmp_ln118_1_reg_1132.read()[0].to_bool())? min_distance_list_2_2_fu_108.read(): min_distance_list_2_9_fu_648_p3.read());
}

void knn_vote::thread_min_distance_list_2_11_fu_661_p3() {
    min_distance_list_2_11_fu_661_p3 = (!icmp_ln118_reg_1124.read()[0].is_01())? sc_lv<32>(): ((icmp_ln118_reg_1124.read()[0].to_bool())? min_distance_list_2_21_reg_1103.read(): min_distance_list_2_3_fu_104.read());
}

void knn_vote::thread_min_distance_list_2_12_fu_667_p3() {
    min_distance_list_2_12_fu_667_p3 = (!icmp_ln118_1_reg_1132.read()[0].is_01())? sc_lv<32>(): ((icmp_ln118_1_reg_1132.read()[0].to_bool())? min_distance_list_2_3_fu_104.read(): min_distance_list_2_11_fu_661_p3.read());
}

void knn_vote::thread_min_distance_list_2_13_fu_674_p3() {
    min_distance_list_2_13_fu_674_p3 = (!icmp_ln118_1_reg_1132.read()[0].is_01())? sc_lv<32>(): ((icmp_ln118_1_reg_1132.read()[0].to_bool())? min_distance_list_2_21_reg_1103.read(): min_distance_list_2_1_fu_100.read());
}

void knn_vote::thread_min_distance_list_2_14_fu_768_p3() {
    min_distance_list_2_14_fu_768_p3 = (!icmp_ln116_fu_596_p2.read()[0].is_01())? sc_lv<32>(): ((icmp_ln116_fu_596_p2.read()[0].to_bool())? min_distance_list_2_10_fu_654_p3.read(): min_distance_list_2_2_fu_108.read());
}

void knn_vote::thread_min_distance_list_2_15_fu_776_p3() {
    min_distance_list_2_15_fu_776_p3 = (!icmp_ln116_fu_596_p2.read()[0].is_01())? sc_lv<32>(): ((icmp_ln116_fu_596_p2.read()[0].to_bool())? min_distance_list_2_12_fu_667_p3.read(): min_distance_list_2_3_fu_104.read());
}

void knn_vote::thread_min_distance_list_2_16_fu_784_p3() {
    min_distance_list_2_16_fu_784_p3 = (!icmp_ln116_fu_596_p2.read()[0].is_01())? sc_lv<32>(): ((icmp_ln116_fu_596_p2.read()[0].to_bool())? min_distance_list_2_13_fu_674_p3.read(): min_distance_list_2_1_fu_100.read());
}

void knn_vote::thread_min_distance_list_2_17_fu_816_p3() {
    min_distance_list_2_17_fu_816_p3 = (!icmp_ln111_fu_576_p2.read()[0].is_01())? sc_lv<32>(): ((icmp_ln111_fu_576_p2.read()[0].to_bool())? min_distance_list_2_5_fu_616_p3.read(): min_distance_list_2_14_fu_768_p3.read());
}

void knn_vote::thread_min_distance_list_2_18_fu_824_p3() {
    min_distance_list_2_18_fu_824_p3 = (!icmp_ln111_fu_576_p2.read()[0].is_01())? sc_lv<32>(): ((icmp_ln111_fu_576_p2.read()[0].to_bool())? min_distance_list_2_6_fu_624_p3.read(): min_distance_list_2_15_fu_776_p3.read());
}

void knn_vote::thread_min_distance_list_2_19_fu_832_p3() {
    min_distance_list_2_19_fu_832_p3 = (!icmp_ln111_fu_576_p2.read()[0].is_01())? sc_lv<32>(): ((icmp_ln111_fu_576_p2.read()[0].to_bool())? min_distance_list_2_7_fu_632_p3.read(): min_distance_list_2_16_fu_784_p3.read());
}

void knn_vote::thread_min_distance_list_2_20_fu_588_p3() {
    min_distance_list_2_20_fu_588_p3 = (!icmp_ln113_fu_582_p2.read()[0].is_01())? sc_lv<32>(): ((icmp_ln113_fu_582_p2.read()[0].to_bool())? min_distance_list_2_1_fu_100.read(): min_distance_list_2_3_fu_104.read());
}

void knn_vote::thread_min_distance_list_2_21_fu_475_p1() {
    min_distance_list_2_21_fu_475_p1 = esl_sext<32,11>(knn_set_q0.read());
}

void knn_vote::thread_min_distance_list_2_22_reg_992() {
    min_distance_list_2_22_reg_992 = ap_const_lv32_100;
}

void knn_vote::thread_min_distance_list_2_5_fu_616_p3() {
    min_distance_list_2_5_fu_616_p3 = (!icmp_ln113_1_fu_610_p2.read()[0].is_01())? sc_lv<32>(): ((icmp_ln113_1_fu_610_p2.read()[0].to_bool())? min_distance_list_2_2_fu_108.read(): min_distance_list_2_fu_602_p3.read());
}

void knn_vote::thread_min_distance_list_2_6_fu_624_p3() {
    min_distance_list_2_6_fu_624_p3 = (!icmp_ln113_1_fu_610_p2.read()[0].is_01())? sc_lv<32>(): ((icmp_ln113_1_fu_610_p2.read()[0].to_bool())? min_distance_list_2_3_fu_104.read(): min_distance_list_2_20_fu_588_p3.read());
}

void knn_vote::thread_min_distance_list_2_7_fu_632_p3() {
    min_distance_list_2_7_fu_632_p3 = (!icmp_ln113_1_fu_610_p2.read()[0].is_01())? sc_lv<32>(): ((icmp_ln113_1_fu_610_p2.read()[0].to_bool())? min_distance_list_2_20_fu_588_p3.read(): min_distance_list_2_1_fu_100.read());
}

void knn_vote::thread_min_distance_list_2_9_fu_648_p3() {
    min_distance_list_2_9_fu_648_p3 = (!icmp_ln118_reg_1124.read()[0].is_01())? sc_lv<32>(): ((icmp_ln118_reg_1124.read()[0].to_bool())? min_distance_list_2_2_fu_108.read(): min_distance_list_2_21_reg_1103.read());
}

void knn_vote::thread_min_distance_list_2_fu_602_p3() {
    min_distance_list_2_fu_602_p3 = (!icmp_ln113_fu_582_p2.read()[0].is_01())? sc_lv<32>(): ((icmp_ln113_fu_582_p2.read()[0].to_bool())? min_distance_list_2_2_fu_108.read(): min_distance_list_2_3_fu_104.read());
}

void knn_vote::thread_phitmp_fu_528_p3() {
    phitmp_fu_528_p3 = (!icmp_ln105_1_fu_522_p2.read()[0].is_01())? sc_lv<32>(): ((icmp_ln105_1_fu_522_p2.read()[0].to_bool())? zext_ln102_fu_479_p1.read(): pos_0_reg_230.read());
}

void knn_vote::thread_pos_fu_536_p3() {
    pos_fu_536_p3 = (!icmp_ln105_fu_507_p2.read()[0].is_01())? sc_lv<32>(): ((icmp_ln105_fu_507_p2.read()[0].to_bool())? phitmp_fu_528_p3.read(): pos_0_reg_230.read());
}

void knn_vote::thread_r_1_fu_566_p2() {
    r_1_fu_566_p2 = (!r3_0_reg_242.read().is_01() || !ap_const_lv2_3.is_01())? sc_lv<2>(): (sc_biguint<2>(r3_0_reg_242.read()) + sc_bigint<2>(ap_const_lv2_3));
}

void knn_vote::thread_r_fu_489_p2() {
    r_fu_489_p2 = (!r_0_reg_219.read().is_01() || !ap_const_lv2_1.is_01())? sc_lv<2>(): (sc_biguint<2>(r_0_reg_219.read()) + sc_biguint<2>(ap_const_lv2_1));
}

void knn_vote::thread_select_ln139_fu_938_p3() {
    select_ln139_fu_938_p3 = (!icmp_ln139_fu_928_p2.read()[0].is_01())? sc_lv<8>(): ((icmp_ln139_fu_928_p2.read()[0].to_bool())? max_vote_0_reg_264.read(): max_vote_fu_934_p1.read());
}

void knn_vote::thread_sext_ln105_fu_466_p1() {
    sext_ln105_fu_466_p1 = esl_sext<32,7>(add_ln105_fu_461_p2.read());
}

void knn_vote::thread_sext_ln129_fu_894_p1() {
    sext_ln129_fu_894_p1 = esl_sext<64,32>(tmp_1_fu_882_p5.read());
}

void knn_vote::thread_shl_ln_fu_427_p3() {
    shl_ln_fu_427_p3 = esl_concat<4,2>(label_list_2_21_reg_197.read(), ap_const_lv2_0);
}

void knn_vote::thread_sub_ln105_fu_439_p2() {
    sub_ln105_fu_439_p2 = (!zext_ln105_1_fu_435_p1.read().is_01() || !zext_ln96_1_fu_411_p1.read().is_01())? sc_lv<7>(): (sc_biguint<7>(zext_ln105_1_fu_435_p1.read()) - sc_biguint<7>(zext_ln96_1_fu_411_p1.read()));
}

void knn_vote::thread_tmp_4_fu_512_p4() {
    tmp_4_fu_512_p4 = pos_0_reg_230.read().range(31, 2);
}

void knn_vote::thread_trunc_ln118_fu_544_p1() {
    trunc_ln118_fu_544_p1 = pos_0_reg_230.read().range(2-1, 0);
}

void knn_vote::thread_vote_list_address0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state11.read())) {
        vote_list_address0 =  (sc_lv<4>) (zext_ln139_1_fu_918_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read())) {
        vote_list_address0 = vote_list_addr_1_reg_1158.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read())) {
        vote_list_address0 =  (sc_lv<4>) (sext_ln129_fu_894_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        vote_list_address0 =  (sc_lv<4>) (zext_ln91_fu_378_p1.read());
    } else {
        vote_list_address0 = "XXXX";
    }
}

void knn_vote::thread_vote_list_address1() {
    vote_list_address1 =  (sc_lv<4>) (zext_ln139_fu_923_p1.read());
}

void knn_vote::thread_vote_list_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state11.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read()))) {
        vote_list_ce0 = ap_const_logic_1;
    } else {
        vote_list_ce0 = ap_const_logic_0;
    }
}

void knn_vote::thread_vote_list_ce1() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state11.read())) {
        vote_list_ce1 = ap_const_logic_1;
    } else {
        vote_list_ce1 = ap_const_logic_0;
    }
}

void knn_vote::thread_vote_list_d0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read())) {
        vote_list_d0 = add_ln129_fu_899_p2.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        vote_list_d0 = ap_const_lv32_0;
    } else {
        vote_list_d0 =  (sc_lv<32>) ("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX");
    }
}

void knn_vote::thread_vote_list_we0() {
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln88_fu_366_p2.read())) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read()))) {
        vote_list_we0 = ap_const_logic_1;
    } else {
        vote_list_we0 = ap_const_logic_0;
    }
}

void knn_vote::thread_zext_ln102_fu_479_p1() {
    zext_ln102_fu_479_p1 = esl_zext<32,2>(r_0_reg_219.read());
}

void knn_vote::thread_zext_ln105_1_fu_435_p1() {
    zext_ln105_1_fu_435_p1 = esl_zext<7,6>(shl_ln_fu_427_p3.read());
}

void knn_vote::thread_zext_ln105_fu_470_p1() {
    zext_ln105_fu_470_p1 = esl_zext<64,32>(sext_ln105_fu_466_p1.read());
}

void knn_vote::thread_zext_ln111_fu_572_p1() {
    zext_ln111_fu_572_p1 = esl_zext<32,2>(r_1_fu_566_p2.read());
}

void knn_vote::thread_zext_ln139_1_fu_918_p1() {
    zext_ln139_1_fu_918_p1 = esl_zext<64,4>(i5_0_reg_276.read());
}

void knn_vote::thread_zext_ln139_fu_923_p1() {
    zext_ln139_fu_923_p1 = esl_zext<64,8>(max_vote_0_reg_264.read());
}

void knn_vote::thread_zext_ln91_fu_378_p1() {
    zext_ln91_fu_378_p1 = esl_zext<64,4>(i1_0_reg_186.read());
}

void knn_vote::thread_zext_ln96_1_fu_411_p1() {
    zext_ln96_1_fu_411_p1 = esl_zext<7,4>(label_list_2_21_reg_197.read());
}

void knn_vote::thread_zext_ln96_fu_407_p1() {
    zext_ln96_fu_407_p1 = esl_zext<32,4>(label_list_2_21_reg_197.read());
}

void knn_vote::thread_zext_ln98_fu_445_p1() {
    zext_ln98_fu_445_p1 = esl_zext<7,2>(j_0_reg_208.read());
}

void knn_vote::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
                ap_NS_fsm = ap_ST_fsm_state2;
            } else {
                ap_NS_fsm = ap_ST_fsm_state1;
            }
            break;
        case 2 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln81_fu_324_p2.read()))) {
                ap_NS_fsm = ap_ST_fsm_state3;
            } else {
                ap_NS_fsm = ap_ST_fsm_state2;
            }
            break;
        case 4 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln88_fu_366_p2.read()))) {
                ap_NS_fsm = ap_ST_fsm_state4;
            } else {
                ap_NS_fsm = ap_ST_fsm_state3;
            }
            break;
        case 8 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && esl_seteq<1,1,1>(icmp_ln96_fu_415_p2.read(), ap_const_lv1_1))) {
                ap_NS_fsm = ap_ST_fsm_state9;
            } else {
                ap_NS_fsm = ap_ST_fsm_state5;
            }
            break;
        case 16 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) && esl_seteq<1,1,1>(icmp_ln98_fu_449_p2.read(), ap_const_lv1_1))) {
                ap_NS_fsm = ap_ST_fsm_state4;
            } else {
                ap_NS_fsm = ap_ST_fsm_state6;
            }
            break;
        case 32 : 
            ap_NS_fsm = ap_ST_fsm_state7;
            break;
        case 64 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) && esl_seteq<1,1,1>(icmp_ln102_fu_483_p2.read(), ap_const_lv1_1))) {
                ap_NS_fsm = ap_ST_fsm_state8;
            } else {
                ap_NS_fsm = ap_ST_fsm_state7;
            }
            break;
        case 128 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read()) && esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln108_fu_560_p2.read()))) {
                ap_NS_fsm = ap_ST_fsm_state5;
            } else {
                ap_NS_fsm = ap_ST_fsm_state8;
            }
            break;
        case 256 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read()) && esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln126_fu_870_p2.read()))) {
                ap_NS_fsm = ap_ST_fsm_state11;
            } else {
                ap_NS_fsm = ap_ST_fsm_state10;
            }
            break;
        case 512 : 
            ap_NS_fsm = ap_ST_fsm_state9;
            break;
        case 1024 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state11.read()) && esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln136_fu_906_p2.read()))) {
                ap_NS_fsm = ap_ST_fsm_state1;
            } else {
                ap_NS_fsm = ap_ST_fsm_state12;
            }
            break;
        case 2048 : 
            ap_NS_fsm = ap_ST_fsm_state11;
            break;
        default : 
            ap_NS_fsm =  (sc_lv<12>) ("XXXXXXXXXXXX");
            break;
    }
}

}

